// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dailyActivity.proto

package pomelo.dailyActivity;

public final class DailyActivity {
  private DailyActivity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DailyInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.dailyActivity.DailyInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动id
     * </pre>
     */
    int getId();

    /**
     * <code>optional int32 cur_num = 2;</code>
     *
     * <pre>
     * 当前完成次数
     * </pre>
     */
    boolean hasCurNum();
    /**
     * <code>optional int32 cur_num = 2;</code>
     *
     * <pre>
     * 当前完成次数
     * </pre>
     */
    int getCurNum();

    /**
     * <code>optional int32 max_num = 3;</code>
     *
     * <pre>
     * 每日可参与最大次数（0 表示不限）
     * </pre>
     */
    boolean hasMaxNum();
    /**
     * <code>optional int32 max_num = 3;</code>
     *
     * <pre>
     * 每日可参与最大次数（0 表示不限）
     * </pre>
     */
    int getMaxNum();

    /**
     * <code>optional int32 perDegree = 4;</code>
     *
     * <pre>
     * 每次活跃度
     * </pre>
     */
    boolean hasPerDegree();
    /**
     * <code>optional int32 perDegree = 4;</code>
     *
     * <pre>
     * 每次活跃度
     * </pre>
     */
    int getPerDegree();

    /**
     * <code>optional int32 lvLimit = 5;</code>
     *
     * <pre>
     * 等级限制
     * </pre>
     */
    boolean hasLvLimit();
    /**
     * <code>optional int32 lvLimit = 5;</code>
     *
     * <pre>
     * 等级限制
     * </pre>
     */
    int getLvLimit();

    /**
     * <code>optional string openPeriod = 6;</code>
     *
     * <pre>
     * 开始时间段
     * </pre>
     */
    boolean hasOpenPeriod();
    /**
     * <code>optional string openPeriod = 6;</code>
     *
     * <pre>
     * 开始时间段
     * </pre>
     */
    java.lang.String getOpenPeriod();
    /**
     * <code>optional string openPeriod = 6;</code>
     *
     * <pre>
     * 开始时间段
     * </pre>
     */
    com.google.protobuf.ByteString
        getOpenPeriodBytes();

    /**
     * <code>optional int32 isOver = 7;</code>
     *
     * <pre>
     * 0：不在时间段 1：正在进行中 2：已结束
     * </pre>
     */
    boolean hasIsOver();
    /**
     * <code>optional int32 isOver = 7;</code>
     *
     * <pre>
     * 0：不在时间段 1：正在进行中 2：已结束
     * </pre>
     */
    int getIsOver();

    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    java.util.List<pomelo.item.ItemOuterClass.ItemDetail> 
        getAwardItemList();
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    pomelo.item.ItemOuterClass.ItemDetail getAwardItem(int index);
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    int getAwardItemCount();
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    java.util.List<? extends pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
        getAwardItemOrBuilderList();
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    pomelo.item.ItemOuterClass.ItemDetailOrBuilder getAwardItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pomelo.dailyActivity.DailyInfo}
   *
   * <pre>
   * 日常活动信息
   * </pre>
   */
  public static final class DailyInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.dailyActivity.DailyInfo)
      DailyInfoOrBuilder {
    // Use DailyInfo.newBuilder() to construct.
    private DailyInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DailyInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DailyInfo defaultInstance;
    public static DailyInfo getDefaultInstance() {
      return defaultInstance;
    }

    public DailyInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DailyInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              curNum_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              maxNum_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              perDegree_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              lvLimit_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              openPeriod_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              isOver_ = input.readInt32();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                awardItem_ = new java.util.ArrayList<pomelo.item.ItemOuterClass.ItemDetail>();
                mutable_bitField0_ |= 0x00000080;
              }
              awardItem_.add(input.readMessage(pomelo.item.ItemOuterClass.ItemDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          awardItem_ = java.util.Collections.unmodifiableList(awardItem_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DailyInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DailyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.dailyActivity.DailyActivity.DailyInfo.class, pomelo.dailyActivity.DailyActivity.DailyInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<DailyInfo> PARSER =
        new com.google.protobuf.AbstractParser<DailyInfo>() {
      public DailyInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DailyInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DailyInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活动id
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int CUR_NUM_FIELD_NUMBER = 2;
    private int curNum_;
    /**
     * <code>optional int32 cur_num = 2;</code>
     *
     * <pre>
     * 当前完成次数
     * </pre>
     */
    public boolean hasCurNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cur_num = 2;</code>
     *
     * <pre>
     * 当前完成次数
     * </pre>
     */
    public int getCurNum() {
      return curNum_;
    }

    public static final int MAX_NUM_FIELD_NUMBER = 3;
    private int maxNum_;
    /**
     * <code>optional int32 max_num = 3;</code>
     *
     * <pre>
     * 每日可参与最大次数（0 表示不限）
     * </pre>
     */
    public boolean hasMaxNum() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 max_num = 3;</code>
     *
     * <pre>
     * 每日可参与最大次数（0 表示不限）
     * </pre>
     */
    public int getMaxNum() {
      return maxNum_;
    }

    public static final int PERDEGREE_FIELD_NUMBER = 4;
    private int perDegree_;
    /**
     * <code>optional int32 perDegree = 4;</code>
     *
     * <pre>
     * 每次活跃度
     * </pre>
     */
    public boolean hasPerDegree() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 perDegree = 4;</code>
     *
     * <pre>
     * 每次活跃度
     * </pre>
     */
    public int getPerDegree() {
      return perDegree_;
    }

    public static final int LVLIMIT_FIELD_NUMBER = 5;
    private int lvLimit_;
    /**
     * <code>optional int32 lvLimit = 5;</code>
     *
     * <pre>
     * 等级限制
     * </pre>
     */
    public boolean hasLvLimit() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 lvLimit = 5;</code>
     *
     * <pre>
     * 等级限制
     * </pre>
     */
    public int getLvLimit() {
      return lvLimit_;
    }

    public static final int OPENPERIOD_FIELD_NUMBER = 6;
    private java.lang.Object openPeriod_;
    /**
     * <code>optional string openPeriod = 6;</code>
     *
     * <pre>
     * 开始时间段
     * </pre>
     */
    public boolean hasOpenPeriod() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string openPeriod = 6;</code>
     *
     * <pre>
     * 开始时间段
     * </pre>
     */
    public java.lang.String getOpenPeriod() {
      java.lang.Object ref = openPeriod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          openPeriod_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string openPeriod = 6;</code>
     *
     * <pre>
     * 开始时间段
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOpenPeriodBytes() {
      java.lang.Object ref = openPeriod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        openPeriod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISOVER_FIELD_NUMBER = 7;
    private int isOver_;
    /**
     * <code>optional int32 isOver = 7;</code>
     *
     * <pre>
     * 0：不在时间段 1：正在进行中 2：已结束
     * </pre>
     */
    public boolean hasIsOver() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 isOver = 7;</code>
     *
     * <pre>
     * 0：不在时间段 1：正在进行中 2：已结束
     * </pre>
     */
    public int getIsOver() {
      return isOver_;
    }

    public static final int AWARDITEM_FIELD_NUMBER = 8;
    private java.util.List<pomelo.item.ItemOuterClass.ItemDetail> awardItem_;
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public java.util.List<pomelo.item.ItemOuterClass.ItemDetail> getAwardItemList() {
      return awardItem_;
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public java.util.List<? extends pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
        getAwardItemOrBuilderList() {
      return awardItem_;
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public int getAwardItemCount() {
      return awardItem_.size();
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public pomelo.item.ItemOuterClass.ItemDetail getAwardItem(int index) {
      return awardItem_.get(index);
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public pomelo.item.ItemOuterClass.ItemDetailOrBuilder getAwardItemOrBuilder(
        int index) {
      return awardItem_.get(index);
    }

    private void initFields() {
      id_ = 0;
      curNum_ = 0;
      maxNum_ = 0;
      perDegree_ = 0;
      lvLimit_ = 0;
      openPeriod_ = "";
      isOver_ = 0;
      awardItem_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAwardItemCount(); i++) {
        if (!getAwardItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, curNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, maxNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, perDegree_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, lvLimit_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getOpenPeriodBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, isOver_);
      }
      for (int i = 0; i < awardItem_.size(); i++) {
        output.writeMessage(8, awardItem_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, curNum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, maxNum_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, perDegree_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, lvLimit_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getOpenPeriodBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, isOver_);
      }
      for (int i = 0; i < awardItem_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, awardItem_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.dailyActivity.DailyActivity.DailyInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.dailyActivity.DailyActivity.DailyInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.dailyActivity.DailyInfo}
     *
     * <pre>
     * 日常活动信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.dailyActivity.DailyInfo)
        pomelo.dailyActivity.DailyActivity.DailyInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DailyInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DailyInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.dailyActivity.DailyActivity.DailyInfo.class, pomelo.dailyActivity.DailyActivity.DailyInfo.Builder.class);
      }

      // Construct using pomelo.dailyActivity.DailyActivity.DailyInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAwardItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        curNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        maxNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        perDegree_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        lvLimit_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        openPeriod_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        isOver_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (awardItemBuilder_ == null) {
          awardItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          awardItemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DailyInfo_descriptor;
      }

      public pomelo.dailyActivity.DailyActivity.DailyInfo getDefaultInstanceForType() {
        return pomelo.dailyActivity.DailyActivity.DailyInfo.getDefaultInstance();
      }

      public pomelo.dailyActivity.DailyActivity.DailyInfo build() {
        pomelo.dailyActivity.DailyActivity.DailyInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.dailyActivity.DailyActivity.DailyInfo buildPartial() {
        pomelo.dailyActivity.DailyActivity.DailyInfo result = new pomelo.dailyActivity.DailyActivity.DailyInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.curNum_ = curNum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.maxNum_ = maxNum_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.perDegree_ = perDegree_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lvLimit_ = lvLimit_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.openPeriod_ = openPeriod_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.isOver_ = isOver_;
        if (awardItemBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            awardItem_ = java.util.Collections.unmodifiableList(awardItem_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.awardItem_ = awardItem_;
        } else {
          result.awardItem_ = awardItemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.dailyActivity.DailyActivity.DailyInfo) {
          return mergeFrom((pomelo.dailyActivity.DailyActivity.DailyInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.dailyActivity.DailyActivity.DailyInfo other) {
        if (other == pomelo.dailyActivity.DailyActivity.DailyInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCurNum()) {
          setCurNum(other.getCurNum());
        }
        if (other.hasMaxNum()) {
          setMaxNum(other.getMaxNum());
        }
        if (other.hasPerDegree()) {
          setPerDegree(other.getPerDegree());
        }
        if (other.hasLvLimit()) {
          setLvLimit(other.getLvLimit());
        }
        if (other.hasOpenPeriod()) {
          bitField0_ |= 0x00000020;
          openPeriod_ = other.openPeriod_;
          onChanged();
        }
        if (other.hasIsOver()) {
          setIsOver(other.getIsOver());
        }
        if (awardItemBuilder_ == null) {
          if (!other.awardItem_.isEmpty()) {
            if (awardItem_.isEmpty()) {
              awardItem_ = other.awardItem_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureAwardItemIsMutable();
              awardItem_.addAll(other.awardItem_);
            }
            onChanged();
          }
        } else {
          if (!other.awardItem_.isEmpty()) {
            if (awardItemBuilder_.isEmpty()) {
              awardItemBuilder_.dispose();
              awardItemBuilder_ = null;
              awardItem_ = other.awardItem_;
              bitField0_ = (bitField0_ & ~0x00000080);
              awardItemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAwardItemFieldBuilder() : null;
            } else {
              awardItemBuilder_.addAllMessages(other.awardItem_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getAwardItemCount(); i++) {
          if (!getAwardItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.dailyActivity.DailyActivity.DailyInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.dailyActivity.DailyActivity.DailyInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动id
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动id
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活动id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int curNum_ ;
      /**
       * <code>optional int32 cur_num = 2;</code>
       *
       * <pre>
       * 当前完成次数
       * </pre>
       */
      public boolean hasCurNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cur_num = 2;</code>
       *
       * <pre>
       * 当前完成次数
       * </pre>
       */
      public int getCurNum() {
        return curNum_;
      }
      /**
       * <code>optional int32 cur_num = 2;</code>
       *
       * <pre>
       * 当前完成次数
       * </pre>
       */
      public Builder setCurNum(int value) {
        bitField0_ |= 0x00000002;
        curNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cur_num = 2;</code>
       *
       * <pre>
       * 当前完成次数
       * </pre>
       */
      public Builder clearCurNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        curNum_ = 0;
        onChanged();
        return this;
      }

      private int maxNum_ ;
      /**
       * <code>optional int32 max_num = 3;</code>
       *
       * <pre>
       * 每日可参与最大次数（0 表示不限）
       * </pre>
       */
      public boolean hasMaxNum() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 max_num = 3;</code>
       *
       * <pre>
       * 每日可参与最大次数（0 表示不限）
       * </pre>
       */
      public int getMaxNum() {
        return maxNum_;
      }
      /**
       * <code>optional int32 max_num = 3;</code>
       *
       * <pre>
       * 每日可参与最大次数（0 表示不限）
       * </pre>
       */
      public Builder setMaxNum(int value) {
        bitField0_ |= 0x00000004;
        maxNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_num = 3;</code>
       *
       * <pre>
       * 每日可参与最大次数（0 表示不限）
       * </pre>
       */
      public Builder clearMaxNum() {
        bitField0_ = (bitField0_ & ~0x00000004);
        maxNum_ = 0;
        onChanged();
        return this;
      }

      private int perDegree_ ;
      /**
       * <code>optional int32 perDegree = 4;</code>
       *
       * <pre>
       * 每次活跃度
       * </pre>
       */
      public boolean hasPerDegree() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 perDegree = 4;</code>
       *
       * <pre>
       * 每次活跃度
       * </pre>
       */
      public int getPerDegree() {
        return perDegree_;
      }
      /**
       * <code>optional int32 perDegree = 4;</code>
       *
       * <pre>
       * 每次活跃度
       * </pre>
       */
      public Builder setPerDegree(int value) {
        bitField0_ |= 0x00000008;
        perDegree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 perDegree = 4;</code>
       *
       * <pre>
       * 每次活跃度
       * </pre>
       */
      public Builder clearPerDegree() {
        bitField0_ = (bitField0_ & ~0x00000008);
        perDegree_ = 0;
        onChanged();
        return this;
      }

      private int lvLimit_ ;
      /**
       * <code>optional int32 lvLimit = 5;</code>
       *
       * <pre>
       * 等级限制
       * </pre>
       */
      public boolean hasLvLimit() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 lvLimit = 5;</code>
       *
       * <pre>
       * 等级限制
       * </pre>
       */
      public int getLvLimit() {
        return lvLimit_;
      }
      /**
       * <code>optional int32 lvLimit = 5;</code>
       *
       * <pre>
       * 等级限制
       * </pre>
       */
      public Builder setLvLimit(int value) {
        bitField0_ |= 0x00000010;
        lvLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 lvLimit = 5;</code>
       *
       * <pre>
       * 等级限制
       * </pre>
       */
      public Builder clearLvLimit() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lvLimit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object openPeriod_ = "";
      /**
       * <code>optional string openPeriod = 6;</code>
       *
       * <pre>
       * 开始时间段
       * </pre>
       */
      public boolean hasOpenPeriod() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string openPeriod = 6;</code>
       *
       * <pre>
       * 开始时间段
       * </pre>
       */
      public java.lang.String getOpenPeriod() {
        java.lang.Object ref = openPeriod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            openPeriod_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string openPeriod = 6;</code>
       *
       * <pre>
       * 开始时间段
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOpenPeriodBytes() {
        java.lang.Object ref = openPeriod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          openPeriod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string openPeriod = 6;</code>
       *
       * <pre>
       * 开始时间段
       * </pre>
       */
      public Builder setOpenPeriod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        openPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string openPeriod = 6;</code>
       *
       * <pre>
       * 开始时间段
       * </pre>
       */
      public Builder clearOpenPeriod() {
        bitField0_ = (bitField0_ & ~0x00000020);
        openPeriod_ = getDefaultInstance().getOpenPeriod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string openPeriod = 6;</code>
       *
       * <pre>
       * 开始时间段
       * </pre>
       */
      public Builder setOpenPeriodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        openPeriod_ = value;
        onChanged();
        return this;
      }

      private int isOver_ ;
      /**
       * <code>optional int32 isOver = 7;</code>
       *
       * <pre>
       * 0：不在时间段 1：正在进行中 2：已结束
       * </pre>
       */
      public boolean hasIsOver() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 isOver = 7;</code>
       *
       * <pre>
       * 0：不在时间段 1：正在进行中 2：已结束
       * </pre>
       */
      public int getIsOver() {
        return isOver_;
      }
      /**
       * <code>optional int32 isOver = 7;</code>
       *
       * <pre>
       * 0：不在时间段 1：正在进行中 2：已结束
       * </pre>
       */
      public Builder setIsOver(int value) {
        bitField0_ |= 0x00000040;
        isOver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 isOver = 7;</code>
       *
       * <pre>
       * 0：不在时间段 1：正在进行中 2：已结束
       * </pre>
       */
      public Builder clearIsOver() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isOver_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pomelo.item.ItemOuterClass.ItemDetail> awardItem_ =
        java.util.Collections.emptyList();
      private void ensureAwardItemIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          awardItem_ = new java.util.ArrayList<pomelo.item.ItemOuterClass.ItemDetail>(awardItem_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.item.ItemOuterClass.ItemDetail, pomelo.item.ItemOuterClass.ItemDetail.Builder, pomelo.item.ItemOuterClass.ItemDetailOrBuilder> awardItemBuilder_;

      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public java.util.List<pomelo.item.ItemOuterClass.ItemDetail> getAwardItemList() {
        if (awardItemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(awardItem_);
        } else {
          return awardItemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public int getAwardItemCount() {
        if (awardItemBuilder_ == null) {
          return awardItem_.size();
        } else {
          return awardItemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail getAwardItem(int index) {
        if (awardItemBuilder_ == null) {
          return awardItem_.get(index);
        } else {
          return awardItemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder setAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail value) {
        if (awardItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardItemIsMutable();
          awardItem_.set(index, value);
          onChanged();
        } else {
          awardItemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder setAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail.Builder builderForValue) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.set(index, builderForValue.build());
          onChanged();
        } else {
          awardItemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(pomelo.item.ItemOuterClass.ItemDetail value) {
        if (awardItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardItemIsMutable();
          awardItem_.add(value);
          onChanged();
        } else {
          awardItemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail value) {
        if (awardItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardItemIsMutable();
          awardItem_.add(index, value);
          onChanged();
        } else {
          awardItemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(
          pomelo.item.ItemOuterClass.ItemDetail.Builder builderForValue) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.add(builderForValue.build());
          onChanged();
        } else {
          awardItemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail.Builder builderForValue) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.add(index, builderForValue.build());
          onChanged();
        } else {
          awardItemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAllAwardItem(
          java.lang.Iterable<? extends pomelo.item.ItemOuterClass.ItemDetail> values) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, awardItem_);
          onChanged();
        } else {
          awardItemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder clearAwardItem() {
        if (awardItemBuilder_ == null) {
          awardItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          awardItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder removeAwardItem(int index) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.remove(index);
          onChanged();
        } else {
          awardItemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail.Builder getAwardItemBuilder(
          int index) {
        return getAwardItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetailOrBuilder getAwardItemOrBuilder(
          int index) {
        if (awardItemBuilder_ == null) {
          return awardItem_.get(index);  } else {
          return awardItemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public java.util.List<? extends pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
           getAwardItemOrBuilderList() {
        if (awardItemBuilder_ != null) {
          return awardItemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(awardItem_);
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail.Builder addAwardItemBuilder() {
        return getAwardItemFieldBuilder().addBuilder(
            pomelo.item.ItemOuterClass.ItemDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail.Builder addAwardItemBuilder(
          int index) {
        return getAwardItemFieldBuilder().addBuilder(
            index, pomelo.item.ItemOuterClass.ItemDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 8;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public java.util.List<pomelo.item.ItemOuterClass.ItemDetail.Builder> 
           getAwardItemBuilderList() {
        return getAwardItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.item.ItemOuterClass.ItemDetail, pomelo.item.ItemOuterClass.ItemDetail.Builder, pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
          getAwardItemFieldBuilder() {
        if (awardItemBuilder_ == null) {
          awardItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pomelo.item.ItemOuterClass.ItemDetail, pomelo.item.ItemOuterClass.ItemDetail.Builder, pomelo.item.ItemOuterClass.ItemDetailOrBuilder>(
                  awardItem_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          awardItem_ = null;
        }
        return awardItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.dailyActivity.DailyInfo)
    }

    static {
      defaultInstance = new DailyInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.dailyActivity.DailyInfo)
  }

  public interface DegreeInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.dailyActivity.DegreeInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活跃度id
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活跃度id
     * </pre>
     */
    int getId();

    /**
     * <code>optional int32 needDegree = 2;</code>
     *
     * <pre>
     * 所需活跃度
     * </pre>
     */
    boolean hasNeedDegree();
    /**
     * <code>optional int32 needDegree = 2;</code>
     *
     * <pre>
     * 所需活跃度
     * </pre>
     */
    int getNeedDegree();

    /**
     * <code>optional int32 state = 3;</code>
     *
     * <pre>
     * 领取状态 0 ：未达到  1：可领取 2：已领取
     * </pre>
     */
    boolean hasState();
    /**
     * <code>optional int32 state = 3;</code>
     *
     * <pre>
     * 领取状态 0 ：未达到  1：可领取 2：已领取
     * </pre>
     */
    int getState();

    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    java.util.List<pomelo.item.ItemOuterClass.ItemDetail> 
        getAwardItemList();
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    pomelo.item.ItemOuterClass.ItemDetail getAwardItem(int index);
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    int getAwardItemCount();
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    java.util.List<? extends pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
        getAwardItemOrBuilderList();
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    pomelo.item.ItemOuterClass.ItemDetailOrBuilder getAwardItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pomelo.dailyActivity.DegreeInfo}
   *
   * <pre>
   * 活跃度奖励
   * </pre>
   */
  public static final class DegreeInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.dailyActivity.DegreeInfo)
      DegreeInfoOrBuilder {
    // Use DegreeInfo.newBuilder() to construct.
    private DegreeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DegreeInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DegreeInfo defaultInstance;
    public static DegreeInfo getDefaultInstance() {
      return defaultInstance;
    }

    public DegreeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DegreeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              needDegree_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              state_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                awardItem_ = new java.util.ArrayList<pomelo.item.ItemOuterClass.ItemDetail>();
                mutable_bitField0_ |= 0x00000008;
              }
              awardItem_.add(input.readMessage(pomelo.item.ItemOuterClass.ItemDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          awardItem_ = java.util.Collections.unmodifiableList(awardItem_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DegreeInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DegreeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.dailyActivity.DailyActivity.DegreeInfo.class, pomelo.dailyActivity.DailyActivity.DegreeInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<DegreeInfo> PARSER =
        new com.google.protobuf.AbstractParser<DegreeInfo>() {
      public DegreeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DegreeInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DegreeInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活跃度id
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 活跃度id
     * </pre>
     */
    public int getId() {
      return id_;
    }

    public static final int NEEDDEGREE_FIELD_NUMBER = 2;
    private int needDegree_;
    /**
     * <code>optional int32 needDegree = 2;</code>
     *
     * <pre>
     * 所需活跃度
     * </pre>
     */
    public boolean hasNeedDegree() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 needDegree = 2;</code>
     *
     * <pre>
     * 所需活跃度
     * </pre>
     */
    public int getNeedDegree() {
      return needDegree_;
    }

    public static final int STATE_FIELD_NUMBER = 3;
    private int state_;
    /**
     * <code>optional int32 state = 3;</code>
     *
     * <pre>
     * 领取状态 0 ：未达到  1：可领取 2：已领取
     * </pre>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 state = 3;</code>
     *
     * <pre>
     * 领取状态 0 ：未达到  1：可领取 2：已领取
     * </pre>
     */
    public int getState() {
      return state_;
    }

    public static final int AWARDITEM_FIELD_NUMBER = 4;
    private java.util.List<pomelo.item.ItemOuterClass.ItemDetail> awardItem_;
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public java.util.List<pomelo.item.ItemOuterClass.ItemDetail> getAwardItemList() {
      return awardItem_;
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public java.util.List<? extends pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
        getAwardItemOrBuilderList() {
      return awardItem_;
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public int getAwardItemCount() {
      return awardItem_.size();
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public pomelo.item.ItemOuterClass.ItemDetail getAwardItem(int index) {
      return awardItem_.get(index);
    }
    /**
     * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
     *
     * <pre>
     * 奖励道具
     * </pre>
     */
    public pomelo.item.ItemOuterClass.ItemDetailOrBuilder getAwardItemOrBuilder(
        int index) {
      return awardItem_.get(index);
    }

    private void initFields() {
      id_ = 0;
      needDegree_ = 0;
      state_ = 0;
      awardItem_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAwardItemCount(); i++) {
        if (!getAwardItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, needDegree_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, state_);
      }
      for (int i = 0; i < awardItem_.size(); i++) {
        output.writeMessage(4, awardItem_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, needDegree_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, state_);
      }
      for (int i = 0; i < awardItem_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, awardItem_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.dailyActivity.DailyActivity.DegreeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.dailyActivity.DailyActivity.DegreeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.dailyActivity.DegreeInfo}
     *
     * <pre>
     * 活跃度奖励
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.dailyActivity.DegreeInfo)
        pomelo.dailyActivity.DailyActivity.DegreeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DegreeInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DegreeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.dailyActivity.DailyActivity.DegreeInfo.class, pomelo.dailyActivity.DailyActivity.DegreeInfo.Builder.class);
      }

      // Construct using pomelo.dailyActivity.DailyActivity.DegreeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAwardItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        needDegree_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (awardItemBuilder_ == null) {
          awardItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          awardItemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.dailyActivity.DailyActivity.internal_static_pomelo_dailyActivity_DegreeInfo_descriptor;
      }

      public pomelo.dailyActivity.DailyActivity.DegreeInfo getDefaultInstanceForType() {
        return pomelo.dailyActivity.DailyActivity.DegreeInfo.getDefaultInstance();
      }

      public pomelo.dailyActivity.DailyActivity.DegreeInfo build() {
        pomelo.dailyActivity.DailyActivity.DegreeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.dailyActivity.DailyActivity.DegreeInfo buildPartial() {
        pomelo.dailyActivity.DailyActivity.DegreeInfo result = new pomelo.dailyActivity.DailyActivity.DegreeInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.needDegree_ = needDegree_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.state_ = state_;
        if (awardItemBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            awardItem_ = java.util.Collections.unmodifiableList(awardItem_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.awardItem_ = awardItem_;
        } else {
          result.awardItem_ = awardItemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.dailyActivity.DailyActivity.DegreeInfo) {
          return mergeFrom((pomelo.dailyActivity.DailyActivity.DegreeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.dailyActivity.DailyActivity.DegreeInfo other) {
        if (other == pomelo.dailyActivity.DailyActivity.DegreeInfo.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasNeedDegree()) {
          setNeedDegree(other.getNeedDegree());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (awardItemBuilder_ == null) {
          if (!other.awardItem_.isEmpty()) {
            if (awardItem_.isEmpty()) {
              awardItem_ = other.awardItem_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAwardItemIsMutable();
              awardItem_.addAll(other.awardItem_);
            }
            onChanged();
          }
        } else {
          if (!other.awardItem_.isEmpty()) {
            if (awardItemBuilder_.isEmpty()) {
              awardItemBuilder_.dispose();
              awardItemBuilder_ = null;
              awardItem_ = other.awardItem_;
              bitField0_ = (bitField0_ & ~0x00000008);
              awardItemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAwardItemFieldBuilder() : null;
            } else {
              awardItemBuilder_.addAllMessages(other.awardItem_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getAwardItemCount(); i++) {
          if (!getAwardItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.dailyActivity.DailyActivity.DegreeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.dailyActivity.DailyActivity.DegreeInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活跃度id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活跃度id
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活跃度id
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 活跃度id
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int needDegree_ ;
      /**
       * <code>optional int32 needDegree = 2;</code>
       *
       * <pre>
       * 所需活跃度
       * </pre>
       */
      public boolean hasNeedDegree() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 needDegree = 2;</code>
       *
       * <pre>
       * 所需活跃度
       * </pre>
       */
      public int getNeedDegree() {
        return needDegree_;
      }
      /**
       * <code>optional int32 needDegree = 2;</code>
       *
       * <pre>
       * 所需活跃度
       * </pre>
       */
      public Builder setNeedDegree(int value) {
        bitField0_ |= 0x00000002;
        needDegree_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 needDegree = 2;</code>
       *
       * <pre>
       * 所需活跃度
       * </pre>
       */
      public Builder clearNeedDegree() {
        bitField0_ = (bitField0_ & ~0x00000002);
        needDegree_ = 0;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>optional int32 state = 3;</code>
       *
       * <pre>
       * 领取状态 0 ：未达到  1：可领取 2：已领取
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 state = 3;</code>
       *
       * <pre>
       * 领取状态 0 ：未达到  1：可领取 2：已领取
       * </pre>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>optional int32 state = 3;</code>
       *
       * <pre>
       * 领取状态 0 ：未达到  1：可领取 2：已领取
       * </pre>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000004;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 state = 3;</code>
       *
       * <pre>
       * 领取状态 0 ：未达到  1：可领取 2：已领取
       * </pre>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pomelo.item.ItemOuterClass.ItemDetail> awardItem_ =
        java.util.Collections.emptyList();
      private void ensureAwardItemIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          awardItem_ = new java.util.ArrayList<pomelo.item.ItemOuterClass.ItemDetail>(awardItem_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.item.ItemOuterClass.ItemDetail, pomelo.item.ItemOuterClass.ItemDetail.Builder, pomelo.item.ItemOuterClass.ItemDetailOrBuilder> awardItemBuilder_;

      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public java.util.List<pomelo.item.ItemOuterClass.ItemDetail> getAwardItemList() {
        if (awardItemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(awardItem_);
        } else {
          return awardItemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public int getAwardItemCount() {
        if (awardItemBuilder_ == null) {
          return awardItem_.size();
        } else {
          return awardItemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail getAwardItem(int index) {
        if (awardItemBuilder_ == null) {
          return awardItem_.get(index);
        } else {
          return awardItemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder setAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail value) {
        if (awardItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardItemIsMutable();
          awardItem_.set(index, value);
          onChanged();
        } else {
          awardItemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder setAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail.Builder builderForValue) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.set(index, builderForValue.build());
          onChanged();
        } else {
          awardItemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(pomelo.item.ItemOuterClass.ItemDetail value) {
        if (awardItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardItemIsMutable();
          awardItem_.add(value);
          onChanged();
        } else {
          awardItemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail value) {
        if (awardItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAwardItemIsMutable();
          awardItem_.add(index, value);
          onChanged();
        } else {
          awardItemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(
          pomelo.item.ItemOuterClass.ItemDetail.Builder builderForValue) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.add(builderForValue.build());
          onChanged();
        } else {
          awardItemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAwardItem(
          int index, pomelo.item.ItemOuterClass.ItemDetail.Builder builderForValue) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.add(index, builderForValue.build());
          onChanged();
        } else {
          awardItemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder addAllAwardItem(
          java.lang.Iterable<? extends pomelo.item.ItemOuterClass.ItemDetail> values) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, awardItem_);
          onChanged();
        } else {
          awardItemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder clearAwardItem() {
        if (awardItemBuilder_ == null) {
          awardItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          awardItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public Builder removeAwardItem(int index) {
        if (awardItemBuilder_ == null) {
          ensureAwardItemIsMutable();
          awardItem_.remove(index);
          onChanged();
        } else {
          awardItemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail.Builder getAwardItemBuilder(
          int index) {
        return getAwardItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetailOrBuilder getAwardItemOrBuilder(
          int index) {
        if (awardItemBuilder_ == null) {
          return awardItem_.get(index);  } else {
          return awardItemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public java.util.List<? extends pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
           getAwardItemOrBuilderList() {
        if (awardItemBuilder_ != null) {
          return awardItemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(awardItem_);
        }
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail.Builder addAwardItemBuilder() {
        return getAwardItemFieldBuilder().addBuilder(
            pomelo.item.ItemOuterClass.ItemDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public pomelo.item.ItemOuterClass.ItemDetail.Builder addAwardItemBuilder(
          int index) {
        return getAwardItemFieldBuilder().addBuilder(
            index, pomelo.item.ItemOuterClass.ItemDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.item.ItemDetail awardItem = 4;</code>
       *
       * <pre>
       * 奖励道具
       * </pre>
       */
      public java.util.List<pomelo.item.ItemOuterClass.ItemDetail.Builder> 
           getAwardItemBuilderList() {
        return getAwardItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.item.ItemOuterClass.ItemDetail, pomelo.item.ItemOuterClass.ItemDetail.Builder, pomelo.item.ItemOuterClass.ItemDetailOrBuilder> 
          getAwardItemFieldBuilder() {
        if (awardItemBuilder_ == null) {
          awardItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pomelo.item.ItemOuterClass.ItemDetail, pomelo.item.ItemOuterClass.ItemDetail.Builder, pomelo.item.ItemOuterClass.ItemDetailOrBuilder>(
                  awardItem_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          awardItem_ = null;
        }
        return awardItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.dailyActivity.DegreeInfo)
    }

    static {
      defaultInstance = new DegreeInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.dailyActivity.DegreeInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_dailyActivity_DailyInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_dailyActivity_DailyInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_dailyActivity_DegreeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_dailyActivity_DegreeInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023dailyActivity.proto\022\024pomelo.dailyActiv" +
      "ity\032\nitem.proto\"\255\001\n\tDailyInfo\022\n\n\002id\030\001 \002(" +
      "\005\022\017\n\007cur_num\030\002 \001(\005\022\017\n\007max_num\030\003 \001(\005\022\021\n\tp" +
      "erDegree\030\004 \001(\005\022\017\n\007lvLimit\030\005 \001(\005\022\022\n\nopenP" +
      "eriod\030\006 \001(\t\022\016\n\006isOver\030\007 \001(\005\022*\n\tawardItem" +
      "\030\010 \003(\0132\027.pomelo.item.ItemDetail\"g\n\nDegre" +
      "eInfo\022\n\n\002id\030\001 \002(\005\022\022\n\nneedDegree\030\002 \001(\005\022\r\n" +
      "\005state\030\003 \001(\005\022*\n\tawardItem\030\004 \003(\0132\027.pomelo" +
      ".item.ItemDetail"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pomelo.item.ItemOuterClass.getDescriptor(),
        }, assigner);
    internal_static_pomelo_dailyActivity_DailyInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pomelo_dailyActivity_DailyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_dailyActivity_DailyInfo_descriptor,
        new java.lang.String[] { "Id", "CurNum", "MaxNum", "PerDegree", "LvLimit", "OpenPeriod", "IsOver", "AwardItem", });
    internal_static_pomelo_dailyActivity_DegreeInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pomelo_dailyActivity_DegreeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_dailyActivity_DegreeInfo_descriptor,
        new java.lang.String[] { "Id", "NeedDegree", "State", "AwardItem", });
    pomelo.item.ItemOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
