// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gateHandler.proto

package pomelo.gate;

public final class GateHandler {
  private GateHandler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QueryEntryRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.gate.QueryEntryRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string c2s_uid = 1;</code>
     */
    boolean hasC2SUid();
    /**
     * <code>required string c2s_uid = 1;</code>
     */
    java.lang.String getC2SUid();
    /**
     * <code>required string c2s_uid = 1;</code>
     */
    com.google.protobuf.ByteString
        getC2SUidBytes();

    /**
     * <code>required string c2s_sign = 2;</code>
     */
    boolean hasC2SSign();
    /**
     * <code>required string c2s_sign = 2;</code>
     */
    java.lang.String getC2SSign();
    /**
     * <code>required string c2s_sign = 2;</code>
     */
    com.google.protobuf.ByteString
        getC2SSignBytes();

    /**
     * <code>required string c2s_time = 3;</code>
     */
    boolean hasC2STime();
    /**
     * <code>required string c2s_time = 3;</code>
     */
    java.lang.String getC2STime();
    /**
     * <code>required string c2s_time = 3;</code>
     */
    com.google.protobuf.ByteString
        getC2STimeBytes();

    /**
     * <code>optional int32 c2s_logicServerId = 4;</code>
     */
    boolean hasC2SLogicServerId();
    /**
     * <code>optional int32 c2s_logicServerId = 4;</code>
     */
    int getC2SLogicServerId();
  }
  /**
   * Protobuf type {@code pomelo.gate.QueryEntryRequest}
   */
  public static final class QueryEntryRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.gate.QueryEntryRequest)
      QueryEntryRequestOrBuilder {
    // Use QueryEntryRequest.newBuilder() to construct.
    private QueryEntryRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueryEntryRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueryEntryRequest defaultInstance;
    public static QueryEntryRequest getDefaultInstance() {
      return defaultInstance;
    }

    public QueryEntryRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueryEntryRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              c2SUid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              c2SSign_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              c2STime_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              c2SLogicServerId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.gate.GateHandler.QueryEntryRequest.class, pomelo.gate.GateHandler.QueryEntryRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<QueryEntryRequest> PARSER =
        new com.google.protobuf.AbstractParser<QueryEntryRequest>() {
      public QueryEntryRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryEntryRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QueryEntryRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int C2S_UID_FIELD_NUMBER = 1;
    private java.lang.Object c2SUid_;
    /**
     * <code>required string c2s_uid = 1;</code>
     */
    public boolean hasC2SUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string c2s_uid = 1;</code>
     */
    public java.lang.String getC2SUid() {
      java.lang.Object ref = c2SUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c2SUid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string c2s_uid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getC2SUidBytes() {
      java.lang.Object ref = c2SUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c2SUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C2S_SIGN_FIELD_NUMBER = 2;
    private java.lang.Object c2SSign_;
    /**
     * <code>required string c2s_sign = 2;</code>
     */
    public boolean hasC2SSign() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string c2s_sign = 2;</code>
     */
    public java.lang.String getC2SSign() {
      java.lang.Object ref = c2SSign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c2SSign_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string c2s_sign = 2;</code>
     */
    public com.google.protobuf.ByteString
        getC2SSignBytes() {
      java.lang.Object ref = c2SSign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c2SSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C2S_TIME_FIELD_NUMBER = 3;
    private java.lang.Object c2STime_;
    /**
     * <code>required string c2s_time = 3;</code>
     */
    public boolean hasC2STime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string c2s_time = 3;</code>
     */
    public java.lang.String getC2STime() {
      java.lang.Object ref = c2STime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          c2STime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string c2s_time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getC2STimeBytes() {
      java.lang.Object ref = c2STime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        c2STime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int C2S_LOGICSERVERID_FIELD_NUMBER = 4;
    private int c2SLogicServerId_;
    /**
     * <code>optional int32 c2s_logicServerId = 4;</code>
     */
    public boolean hasC2SLogicServerId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 c2s_logicServerId = 4;</code>
     */
    public int getC2SLogicServerId() {
      return c2SLogicServerId_;
    }

    private void initFields() {
      c2SUid_ = "";
      c2SSign_ = "";
      c2STime_ = "";
      c2SLogicServerId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasC2SUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasC2SSign()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasC2STime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getC2SUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getC2SSignBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getC2STimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, c2SLogicServerId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getC2SUidBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getC2SSignBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getC2STimeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, c2SLogicServerId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.gate.GateHandler.QueryEntryRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.gate.GateHandler.QueryEntryRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.gate.QueryEntryRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.gate.QueryEntryRequest)
        pomelo.gate.GateHandler.QueryEntryRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.gate.GateHandler.QueryEntryRequest.class, pomelo.gate.GateHandler.QueryEntryRequest.Builder.class);
      }

      // Construct using pomelo.gate.GateHandler.QueryEntryRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c2SUid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        c2SSign_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        c2STime_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        c2SLogicServerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryRequest_descriptor;
      }

      public pomelo.gate.GateHandler.QueryEntryRequest getDefaultInstanceForType() {
        return pomelo.gate.GateHandler.QueryEntryRequest.getDefaultInstance();
      }

      public pomelo.gate.GateHandler.QueryEntryRequest build() {
        pomelo.gate.GateHandler.QueryEntryRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.gate.GateHandler.QueryEntryRequest buildPartial() {
        pomelo.gate.GateHandler.QueryEntryRequest result = new pomelo.gate.GateHandler.QueryEntryRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c2SUid_ = c2SUid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.c2SSign_ = c2SSign_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.c2STime_ = c2STime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.c2SLogicServerId_ = c2SLogicServerId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.gate.GateHandler.QueryEntryRequest) {
          return mergeFrom((pomelo.gate.GateHandler.QueryEntryRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.gate.GateHandler.QueryEntryRequest other) {
        if (other == pomelo.gate.GateHandler.QueryEntryRequest.getDefaultInstance()) return this;
        if (other.hasC2SUid()) {
          bitField0_ |= 0x00000001;
          c2SUid_ = other.c2SUid_;
          onChanged();
        }
        if (other.hasC2SSign()) {
          bitField0_ |= 0x00000002;
          c2SSign_ = other.c2SSign_;
          onChanged();
        }
        if (other.hasC2STime()) {
          bitField0_ |= 0x00000004;
          c2STime_ = other.c2STime_;
          onChanged();
        }
        if (other.hasC2SLogicServerId()) {
          setC2SLogicServerId(other.getC2SLogicServerId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasC2SUid()) {
          
          return false;
        }
        if (!hasC2SSign()) {
          
          return false;
        }
        if (!hasC2STime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.gate.GateHandler.QueryEntryRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.gate.GateHandler.QueryEntryRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object c2SUid_ = "";
      /**
       * <code>required string c2s_uid = 1;</code>
       */
      public boolean hasC2SUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string c2s_uid = 1;</code>
       */
      public java.lang.String getC2SUid() {
        java.lang.Object ref = c2SUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            c2SUid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string c2s_uid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getC2SUidBytes() {
        java.lang.Object ref = c2SUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c2SUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string c2s_uid = 1;</code>
       */
      public Builder setC2SUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c2SUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string c2s_uid = 1;</code>
       */
      public Builder clearC2SUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c2SUid_ = getDefaultInstance().getC2SUid();
        onChanged();
        return this;
      }
      /**
       * <code>required string c2s_uid = 1;</code>
       */
      public Builder setC2SUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        c2SUid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object c2SSign_ = "";
      /**
       * <code>required string c2s_sign = 2;</code>
       */
      public boolean hasC2SSign() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string c2s_sign = 2;</code>
       */
      public java.lang.String getC2SSign() {
        java.lang.Object ref = c2SSign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            c2SSign_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string c2s_sign = 2;</code>
       */
      public com.google.protobuf.ByteString
          getC2SSignBytes() {
        java.lang.Object ref = c2SSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c2SSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string c2s_sign = 2;</code>
       */
      public Builder setC2SSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c2SSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string c2s_sign = 2;</code>
       */
      public Builder clearC2SSign() {
        bitField0_ = (bitField0_ & ~0x00000002);
        c2SSign_ = getDefaultInstance().getC2SSign();
        onChanged();
        return this;
      }
      /**
       * <code>required string c2s_sign = 2;</code>
       */
      public Builder setC2SSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        c2SSign_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object c2STime_ = "";
      /**
       * <code>required string c2s_time = 3;</code>
       */
      public boolean hasC2STime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string c2s_time = 3;</code>
       */
      public java.lang.String getC2STime() {
        java.lang.Object ref = c2STime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            c2STime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string c2s_time = 3;</code>
       */
      public com.google.protobuf.ByteString
          getC2STimeBytes() {
        java.lang.Object ref = c2STime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          c2STime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string c2s_time = 3;</code>
       */
      public Builder setC2STime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c2STime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string c2s_time = 3;</code>
       */
      public Builder clearC2STime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        c2STime_ = getDefaultInstance().getC2STime();
        onChanged();
        return this;
      }
      /**
       * <code>required string c2s_time = 3;</code>
       */
      public Builder setC2STimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        c2STime_ = value;
        onChanged();
        return this;
      }

      private int c2SLogicServerId_ ;
      /**
       * <code>optional int32 c2s_logicServerId = 4;</code>
       */
      public boolean hasC2SLogicServerId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 c2s_logicServerId = 4;</code>
       */
      public int getC2SLogicServerId() {
        return c2SLogicServerId_;
      }
      /**
       * <code>optional int32 c2s_logicServerId = 4;</code>
       */
      public Builder setC2SLogicServerId(int value) {
        bitField0_ |= 0x00000008;
        c2SLogicServerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 c2s_logicServerId = 4;</code>
       */
      public Builder clearC2SLogicServerId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        c2SLogicServerId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.gate.QueryEntryRequest)
    }

    static {
      defaultInstance = new QueryEntryRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.gate.QueryEntryRequest)
  }

  public interface QueryEntryResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.gate.QueryEntryResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    boolean hasS2CCode();
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    int getS2CCode();

    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    boolean hasS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    java.lang.String getS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getS2CMsgBytes();

    /**
     * <code>optional string s2c_pubHost = 3;</code>
     */
    boolean hasS2CPubHost();
    /**
     * <code>optional string s2c_pubHost = 3;</code>
     */
    java.lang.String getS2CPubHost();
    /**
     * <code>optional string s2c_pubHost = 3;</code>
     */
    com.google.protobuf.ByteString
        getS2CPubHostBytes();

    /**
     * <code>optional int32 s2c_port = 5;</code>
     */
    boolean hasS2CPort();
    /**
     * <code>optional int32 s2c_port = 5;</code>
     */
    int getS2CPort();

    /**
     * <code>optional string s2c_token = 6;</code>
     *
     * <pre>
     *tocken
     * </pre>
     */
    boolean hasS2CToken();
    /**
     * <code>optional string s2c_token = 6;</code>
     *
     * <pre>
     *tocken
     * </pre>
     */
    java.lang.String getS2CToken();
    /**
     * <code>optional string s2c_token = 6;</code>
     *
     * <pre>
     *tocken
     * </pre>
     */
    com.google.protobuf.ByteString
        getS2CTokenBytes();

    /**
     * <code>optional int32 s2c_averageTime = 7;</code>
     */
    boolean hasS2CAverageTime();
    /**
     * <code>optional int32 s2c_averageTime = 7;</code>
     */
    int getS2CAverageTime();

    /**
     * <code>optional int32 s2c_pos = 8;</code>
     */
    boolean hasS2CPos();
    /**
     * <code>optional int32 s2c_pos = 8;</code>
     */
    int getS2CPos();
  }
  /**
   * Protobuf type {@code pomelo.gate.QueryEntryResponse}
   */
  public static final class QueryEntryResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.gate.QueryEntryResponse)
      QueryEntryResponseOrBuilder {
    // Use QueryEntryResponse.newBuilder() to construct.
    private QueryEntryResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private QueryEntryResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final QueryEntryResponse defaultInstance;
    public static QueryEntryResponse getDefaultInstance() {
      return defaultInstance;
    }

    public QueryEntryResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private QueryEntryResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              s2CMsg_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              s2CPubHost_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              s2CPort_ = input.readInt32();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              s2CToken_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000020;
              s2CAverageTime_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000040;
              s2CPos_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.gate.GateHandler.QueryEntryResponse.class, pomelo.gate.GateHandler.QueryEntryResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<QueryEntryResponse> PARSER =
        new com.google.protobuf.AbstractParser<QueryEntryResponse>() {
      public QueryEntryResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryEntryResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<QueryEntryResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_CODE_FIELD_NUMBER = 1;
    private int s2CCode_;
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public boolean hasS2CCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public int getS2CCode() {
      return s2CCode_;
    }

    public static final int S2C_MSG_FIELD_NUMBER = 2;
    private java.lang.Object s2CMsg_;
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public boolean hasS2CMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public java.lang.String getS2CMsg() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getS2CMsgBytes() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_PUBHOST_FIELD_NUMBER = 3;
    private java.lang.Object s2CPubHost_;
    /**
     * <code>optional string s2c_pubHost = 3;</code>
     */
    public boolean hasS2CPubHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string s2c_pubHost = 3;</code>
     */
    public java.lang.String getS2CPubHost() {
      java.lang.Object ref = s2CPubHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CPubHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_pubHost = 3;</code>
     */
    public com.google.protobuf.ByteString
        getS2CPubHostBytes() {
      java.lang.Object ref = s2CPubHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CPubHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_PORT_FIELD_NUMBER = 5;
    private int s2CPort_;
    /**
     * <code>optional int32 s2c_port = 5;</code>
     */
    public boolean hasS2CPort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 s2c_port = 5;</code>
     */
    public int getS2CPort() {
      return s2CPort_;
    }

    public static final int S2C_TOKEN_FIELD_NUMBER = 6;
    private java.lang.Object s2CToken_;
    /**
     * <code>optional string s2c_token = 6;</code>
     *
     * <pre>
     *tocken
     * </pre>
     */
    public boolean hasS2CToken() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string s2c_token = 6;</code>
     *
     * <pre>
     *tocken
     * </pre>
     */
    public java.lang.String getS2CToken() {
      java.lang.Object ref = s2CToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_token = 6;</code>
     *
     * <pre>
     *tocken
     * </pre>
     */
    public com.google.protobuf.ByteString
        getS2CTokenBytes() {
      java.lang.Object ref = s2CToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_AVERAGETIME_FIELD_NUMBER = 7;
    private int s2CAverageTime_;
    /**
     * <code>optional int32 s2c_averageTime = 7;</code>
     */
    public boolean hasS2CAverageTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 s2c_averageTime = 7;</code>
     */
    public int getS2CAverageTime() {
      return s2CAverageTime_;
    }

    public static final int S2C_POS_FIELD_NUMBER = 8;
    private int s2CPos_;
    /**
     * <code>optional int32 s2c_pos = 8;</code>
     */
    public boolean hasS2CPos() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 s2c_pos = 8;</code>
     */
    public int getS2CPos() {
      return s2CPos_;
    }

    private void initFields() {
      s2CCode_ = 0;
      s2CMsg_ = "";
      s2CPubHost_ = "";
      s2CPort_ = 0;
      s2CToken_ = "";
      s2CAverageTime_ = 0;
      s2CPos_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getS2CMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getS2CPubHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, s2CPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(6, getS2CTokenBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(7, s2CAverageTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(8, s2CPos_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getS2CMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getS2CPubHostBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, s2CPort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getS2CTokenBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, s2CAverageTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, s2CPos_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.gate.GateHandler.QueryEntryResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.gate.GateHandler.QueryEntryResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.gate.QueryEntryResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.gate.QueryEntryResponse)
        pomelo.gate.GateHandler.QueryEntryResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.gate.GateHandler.QueryEntryResponse.class, pomelo.gate.GateHandler.QueryEntryResponse.Builder.class);
      }

      // Construct using pomelo.gate.GateHandler.QueryEntryResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CPubHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        s2CPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        s2CToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        s2CAverageTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        s2CPos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.gate.GateHandler.internal_static_pomelo_gate_QueryEntryResponse_descriptor;
      }

      public pomelo.gate.GateHandler.QueryEntryResponse getDefaultInstanceForType() {
        return pomelo.gate.GateHandler.QueryEntryResponse.getDefaultInstance();
      }

      public pomelo.gate.GateHandler.QueryEntryResponse build() {
        pomelo.gate.GateHandler.QueryEntryResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.gate.GateHandler.QueryEntryResponse buildPartial() {
        pomelo.gate.GateHandler.QueryEntryResponse result = new pomelo.gate.GateHandler.QueryEntryResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CCode_ = s2CCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CMsg_ = s2CMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s2CPubHost_ = s2CPubHost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.s2CPort_ = s2CPort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.s2CToken_ = s2CToken_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.s2CAverageTime_ = s2CAverageTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.s2CPos_ = s2CPos_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.gate.GateHandler.QueryEntryResponse) {
          return mergeFrom((pomelo.gate.GateHandler.QueryEntryResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.gate.GateHandler.QueryEntryResponse other) {
        if (other == pomelo.gate.GateHandler.QueryEntryResponse.getDefaultInstance()) return this;
        if (other.hasS2CCode()) {
          setS2CCode(other.getS2CCode());
        }
        if (other.hasS2CMsg()) {
          bitField0_ |= 0x00000002;
          s2CMsg_ = other.s2CMsg_;
          onChanged();
        }
        if (other.hasS2CPubHost()) {
          bitField0_ |= 0x00000004;
          s2CPubHost_ = other.s2CPubHost_;
          onChanged();
        }
        if (other.hasS2CPort()) {
          setS2CPort(other.getS2CPort());
        }
        if (other.hasS2CToken()) {
          bitField0_ |= 0x00000010;
          s2CToken_ = other.s2CToken_;
          onChanged();
        }
        if (other.hasS2CAverageTime()) {
          setS2CAverageTime(other.getS2CAverageTime());
        }
        if (other.hasS2CPos()) {
          setS2CPos(other.getS2CPos());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.gate.GateHandler.QueryEntryResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.gate.GateHandler.QueryEntryResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CCode_ ;
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public boolean hasS2CCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public int getS2CCode() {
        return s2CCode_;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder setS2CCode(int value) {
        bitField0_ |= 0x00000001;
        s2CCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder clearS2CCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object s2CMsg_ = "";
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public boolean hasS2CMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public java.lang.String getS2CMsg() {
        java.lang.Object ref = s2CMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getS2CMsgBytes() {
        java.lang.Object ref = s2CMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder clearS2CMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CMsg_ = getDefaultInstance().getS2CMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s2CPubHost_ = "";
      /**
       * <code>optional string s2c_pubHost = 3;</code>
       */
      public boolean hasS2CPubHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string s2c_pubHost = 3;</code>
       */
      public java.lang.String getS2CPubHost() {
        java.lang.Object ref = s2CPubHost_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CPubHost_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_pubHost = 3;</code>
       */
      public com.google.protobuf.ByteString
          getS2CPubHostBytes() {
        java.lang.Object ref = s2CPubHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CPubHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_pubHost = 3;</code>
       */
      public Builder setS2CPubHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s2CPubHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_pubHost = 3;</code>
       */
      public Builder clearS2CPubHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s2CPubHost_ = getDefaultInstance().getS2CPubHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_pubHost = 3;</code>
       */
      public Builder setS2CPubHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s2CPubHost_ = value;
        onChanged();
        return this;
      }

      private int s2CPort_ ;
      /**
       * <code>optional int32 s2c_port = 5;</code>
       */
      public boolean hasS2CPort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 s2c_port = 5;</code>
       */
      public int getS2CPort() {
        return s2CPort_;
      }
      /**
       * <code>optional int32 s2c_port = 5;</code>
       */
      public Builder setS2CPort(int value) {
        bitField0_ |= 0x00000008;
        s2CPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 s2c_port = 5;</code>
       */
      public Builder clearS2CPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        s2CPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object s2CToken_ = "";
      /**
       * <code>optional string s2c_token = 6;</code>
       *
       * <pre>
       *tocken
       * </pre>
       */
      public boolean hasS2CToken() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string s2c_token = 6;</code>
       *
       * <pre>
       *tocken
       * </pre>
       */
      public java.lang.String getS2CToken() {
        java.lang.Object ref = s2CToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CToken_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_token = 6;</code>
       *
       * <pre>
       *tocken
       * </pre>
       */
      public com.google.protobuf.ByteString
          getS2CTokenBytes() {
        java.lang.Object ref = s2CToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_token = 6;</code>
       *
       * <pre>
       *tocken
       * </pre>
       */
      public Builder setS2CToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        s2CToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_token = 6;</code>
       *
       * <pre>
       *tocken
       * </pre>
       */
      public Builder clearS2CToken() {
        bitField0_ = (bitField0_ & ~0x00000010);
        s2CToken_ = getDefaultInstance().getS2CToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_token = 6;</code>
       *
       * <pre>
       *tocken
       * </pre>
       */
      public Builder setS2CTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        s2CToken_ = value;
        onChanged();
        return this;
      }

      private int s2CAverageTime_ ;
      /**
       * <code>optional int32 s2c_averageTime = 7;</code>
       */
      public boolean hasS2CAverageTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 s2c_averageTime = 7;</code>
       */
      public int getS2CAverageTime() {
        return s2CAverageTime_;
      }
      /**
       * <code>optional int32 s2c_averageTime = 7;</code>
       */
      public Builder setS2CAverageTime(int value) {
        bitField0_ |= 0x00000020;
        s2CAverageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 s2c_averageTime = 7;</code>
       */
      public Builder clearS2CAverageTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        s2CAverageTime_ = 0;
        onChanged();
        return this;
      }

      private int s2CPos_ ;
      /**
       * <code>optional int32 s2c_pos = 8;</code>
       */
      public boolean hasS2CPos() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 s2c_pos = 8;</code>
       */
      public int getS2CPos() {
        return s2CPos_;
      }
      /**
       * <code>optional int32 s2c_pos = 8;</code>
       */
      public Builder setS2CPos(int value) {
        bitField0_ |= 0x00000040;
        s2CPos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 s2c_pos = 8;</code>
       */
      public Builder clearS2CPos() {
        bitField0_ = (bitField0_ & ~0x00000040);
        s2CPos_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.gate.QueryEntryResponse)
    }

    static {
      defaultInstance = new QueryEntryResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.gate.QueryEntryResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_gate_QueryEntryRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_gate_QueryEntryRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_gate_QueryEntryResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_gate_QueryEntryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021gateHandler.proto\022\013pomelo.gate\"c\n\021Quer" +
      "yEntryRequest\022\017\n\007c2s_uid\030\001 \002(\t\022\020\n\010c2s_si" +
      "gn\030\002 \002(\t\022\020\n\010c2s_time\030\003 \002(\t\022\031\n\021c2s_logicS" +
      "erverId\030\004 \001(\005\"\233\001\n\022QueryEntryResponse\022\020\n\010" +
      "s2c_code\030\001 \002(\005\022\017\n\007s2c_msg\030\002 \001(\t\022\023\n\013s2c_p" +
      "ubHost\030\003 \001(\t\022\020\n\010s2c_port\030\005 \001(\005\022\021\n\ts2c_to" +
      "ken\030\006 \001(\t\022\027\n\017s2c_averageTime\030\007 \001(\005\022\017\n\007s2" +
      "c_pos\030\010 \001(\0052c\n\013gateHandler\022T\n\021queryEntry" +
      "Request\022\036.pomelo.gate.QueryEntryRequest\032" +
      "\037.pomelo.gate.QueryEntryResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pomelo_gate_QueryEntryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pomelo_gate_QueryEntryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_gate_QueryEntryRequest_descriptor,
        new java.lang.String[] { "C2SUid", "C2SSign", "C2STime", "C2SLogicServerId", });
    internal_static_pomelo_gate_QueryEntryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pomelo_gate_QueryEntryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_gate_QueryEntryResponse_descriptor,
        new java.lang.String[] { "S2CCode", "S2CMsg", "S2CPubHost", "S2CPort", "S2CToken", "S2CAverageTime", "S2CPos", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
