// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: functionHandler.proto

package pomelo.area;

public final class FunctionHandler {
  private FunctionHandler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TipsParamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.TipsParam)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 diamond = 1;</code>
     */
    boolean hasDiamond();
    /**
     * <code>optional int32 diamond = 1;</code>
     */
    int getDiamond();
  }
  /**
   * Protobuf type {@code pomelo.area.TipsParam}
   */
  public static final class TipsParam extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.TipsParam)
      TipsParamOrBuilder {
    // Use TipsParam.newBuilder() to construct.
    private TipsParam(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TipsParam(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TipsParam defaultInstance;
    public static TipsParam getDefaultInstance() {
      return defaultInstance;
    }

    public TipsParam getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TipsParam(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              diamond_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.FunctionHandler.internal_static_pomelo_area_TipsParam_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.FunctionHandler.internal_static_pomelo_area_TipsParam_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.FunctionHandler.TipsParam.class, pomelo.area.FunctionHandler.TipsParam.Builder.class);
    }

    public static com.google.protobuf.Parser<TipsParam> PARSER =
        new com.google.protobuf.AbstractParser<TipsParam>() {
      public TipsParam parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TipsParam(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TipsParam> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DIAMOND_FIELD_NUMBER = 1;
    private int diamond_;
    /**
     * <code>optional int32 diamond = 1;</code>
     */
    public boolean hasDiamond() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 diamond = 1;</code>
     */
    public int getDiamond() {
      return diamond_;
    }

    private void initFields() {
      diamond_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, diamond_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, diamond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.FunctionHandler.TipsParam parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.FunctionHandler.TipsParam parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.FunctionHandler.TipsParam prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.TipsParam}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.TipsParam)
        pomelo.area.FunctionHandler.TipsParamOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_TipsParam_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_TipsParam_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.FunctionHandler.TipsParam.class, pomelo.area.FunctionHandler.TipsParam.Builder.class);
      }

      // Construct using pomelo.area.FunctionHandler.TipsParam.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        diamond_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_TipsParam_descriptor;
      }

      public pomelo.area.FunctionHandler.TipsParam getDefaultInstanceForType() {
        return pomelo.area.FunctionHandler.TipsParam.getDefaultInstance();
      }

      public pomelo.area.FunctionHandler.TipsParam build() {
        pomelo.area.FunctionHandler.TipsParam result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.FunctionHandler.TipsParam buildPartial() {
        pomelo.area.FunctionHandler.TipsParam result = new pomelo.area.FunctionHandler.TipsParam(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.diamond_ = diamond_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.FunctionHandler.TipsParam) {
          return mergeFrom((pomelo.area.FunctionHandler.TipsParam)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.FunctionHandler.TipsParam other) {
        if (other == pomelo.area.FunctionHandler.TipsParam.getDefaultInstance()) return this;
        if (other.hasDiamond()) {
          setDiamond(other.getDiamond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.FunctionHandler.TipsParam parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.FunctionHandler.TipsParam) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int diamond_ ;
      /**
       * <code>optional int32 diamond = 1;</code>
       */
      public boolean hasDiamond() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 diamond = 1;</code>
       */
      public int getDiamond() {
        return diamond_;
      }
      /**
       * <code>optional int32 diamond = 1;</code>
       */
      public Builder setDiamond(int value) {
        bitField0_ |= 0x00000001;
        diamond_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 diamond = 1;</code>
       */
      public Builder clearDiamond() {
        bitField0_ = (bitField0_ & ~0x00000001);
        diamond_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.TipsParam)
    }

    static {
      defaultInstance = new TipsParam(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.TipsParam)
  }

  public interface FunctionGoToPushOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.FunctionGoToPush)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    boolean hasS2CCode();
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    int getS2CCode();

    /**
     * <code>required int32 s2c_funGoId = 2;</code>
     */
    boolean hasS2CFunGoId();
    /**
     * <code>required int32 s2c_funGoId = 2;</code>
     */
    int getS2CFunGoId();

    /**
     * <code>optional string s2c_itemCode = 3;</code>
     */
    boolean hasS2CItemCode();
    /**
     * <code>optional string s2c_itemCode = 3;</code>
     */
    java.lang.String getS2CItemCode();
    /**
     * <code>optional string s2c_itemCode = 3;</code>
     */
    com.google.protobuf.ByteString
        getS2CItemCodeBytes();

    /**
     * <code>optional string s2c_id = 4;</code>
     */
    boolean hasS2CId();
    /**
     * <code>optional string s2c_id = 4;</code>
     */
    java.lang.String getS2CId();
    /**
     * <code>optional string s2c_id = 4;</code>
     */
    com.google.protobuf.ByteString
        getS2CIdBytes();

    /**
     * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
     */
    boolean hasS2CParam();
    /**
     * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
     */
    pomelo.area.FunctionHandler.TipsParam getS2CParam();
    /**
     * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
     */
    pomelo.area.FunctionHandler.TipsParamOrBuilder getS2CParamOrBuilder();
  }
  /**
   * Protobuf type {@code pomelo.area.FunctionGoToPush}
   */
  public static final class FunctionGoToPush extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.FunctionGoToPush)
      FunctionGoToPushOrBuilder {
    // Use FunctionGoToPush.newBuilder() to construct.
    private FunctionGoToPush(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private FunctionGoToPush(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final FunctionGoToPush defaultInstance;
    public static FunctionGoToPush getDefaultInstance() {
      return defaultInstance;
    }

    public FunctionGoToPush getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private FunctionGoToPush(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              s2CFunGoId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              s2CItemCode_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              s2CId_ = bs;
              break;
            }
            case 42: {
              pomelo.area.FunctionHandler.TipsParam.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = s2CParam_.toBuilder();
              }
              s2CParam_ = input.readMessage(pomelo.area.FunctionHandler.TipsParam.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2CParam_);
                s2CParam_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.FunctionHandler.internal_static_pomelo_area_FunctionGoToPush_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.FunctionHandler.internal_static_pomelo_area_FunctionGoToPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.FunctionHandler.FunctionGoToPush.class, pomelo.area.FunctionHandler.FunctionGoToPush.Builder.class);
    }

    public static com.google.protobuf.Parser<FunctionGoToPush> PARSER =
        new com.google.protobuf.AbstractParser<FunctionGoToPush>() {
      public FunctionGoToPush parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FunctionGoToPush(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<FunctionGoToPush> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_CODE_FIELD_NUMBER = 1;
    private int s2CCode_;
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public boolean hasS2CCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public int getS2CCode() {
      return s2CCode_;
    }

    public static final int S2C_FUNGOID_FIELD_NUMBER = 2;
    private int s2CFunGoId_;
    /**
     * <code>required int32 s2c_funGoId = 2;</code>
     */
    public boolean hasS2CFunGoId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 s2c_funGoId = 2;</code>
     */
    public int getS2CFunGoId() {
      return s2CFunGoId_;
    }

    public static final int S2C_ITEMCODE_FIELD_NUMBER = 3;
    private java.lang.Object s2CItemCode_;
    /**
     * <code>optional string s2c_itemCode = 3;</code>
     */
    public boolean hasS2CItemCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string s2c_itemCode = 3;</code>
     */
    public java.lang.String getS2CItemCode() {
      java.lang.Object ref = s2CItemCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CItemCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_itemCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getS2CItemCodeBytes() {
      java.lang.Object ref = s2CItemCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CItemCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_ID_FIELD_NUMBER = 4;
    private java.lang.Object s2CId_;
    /**
     * <code>optional string s2c_id = 4;</code>
     */
    public boolean hasS2CId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string s2c_id = 4;</code>
     */
    public java.lang.String getS2CId() {
      java.lang.Object ref = s2CId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getS2CIdBytes() {
      java.lang.Object ref = s2CId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_PARAM_FIELD_NUMBER = 5;
    private pomelo.area.FunctionHandler.TipsParam s2CParam_;
    /**
     * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
     */
    public boolean hasS2CParam() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
     */
    public pomelo.area.FunctionHandler.TipsParam getS2CParam() {
      return s2CParam_;
    }
    /**
     * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
     */
    public pomelo.area.FunctionHandler.TipsParamOrBuilder getS2CParamOrBuilder() {
      return s2CParam_;
    }

    private void initFields() {
      s2CCode_ = 0;
      s2CFunGoId_ = 0;
      s2CItemCode_ = "";
      s2CId_ = "";
      s2CParam_ = pomelo.area.FunctionHandler.TipsParam.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS2CFunGoId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, s2CFunGoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getS2CItemCodeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getS2CIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, s2CParam_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, s2CFunGoId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getS2CItemCodeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getS2CIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, s2CParam_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.FunctionHandler.FunctionGoToPush parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.FunctionHandler.FunctionGoToPush prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.FunctionGoToPush}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.FunctionGoToPush)
        pomelo.area.FunctionHandler.FunctionGoToPushOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_FunctionGoToPush_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_FunctionGoToPush_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.FunctionHandler.FunctionGoToPush.class, pomelo.area.FunctionHandler.FunctionGoToPush.Builder.class);
      }

      // Construct using pomelo.area.FunctionHandler.FunctionGoToPush.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CParamFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CFunGoId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CItemCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        s2CId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (s2CParamBuilder_ == null) {
          s2CParam_ = pomelo.area.FunctionHandler.TipsParam.getDefaultInstance();
        } else {
          s2CParamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_FunctionGoToPush_descriptor;
      }

      public pomelo.area.FunctionHandler.FunctionGoToPush getDefaultInstanceForType() {
        return pomelo.area.FunctionHandler.FunctionGoToPush.getDefaultInstance();
      }

      public pomelo.area.FunctionHandler.FunctionGoToPush build() {
        pomelo.area.FunctionHandler.FunctionGoToPush result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.FunctionHandler.FunctionGoToPush buildPartial() {
        pomelo.area.FunctionHandler.FunctionGoToPush result = new pomelo.area.FunctionHandler.FunctionGoToPush(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CCode_ = s2CCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CFunGoId_ = s2CFunGoId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s2CItemCode_ = s2CItemCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.s2CId_ = s2CId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (s2CParamBuilder_ == null) {
          result.s2CParam_ = s2CParam_;
        } else {
          result.s2CParam_ = s2CParamBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.FunctionHandler.FunctionGoToPush) {
          return mergeFrom((pomelo.area.FunctionHandler.FunctionGoToPush)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.FunctionHandler.FunctionGoToPush other) {
        if (other == pomelo.area.FunctionHandler.FunctionGoToPush.getDefaultInstance()) return this;
        if (other.hasS2CCode()) {
          setS2CCode(other.getS2CCode());
        }
        if (other.hasS2CFunGoId()) {
          setS2CFunGoId(other.getS2CFunGoId());
        }
        if (other.hasS2CItemCode()) {
          bitField0_ |= 0x00000004;
          s2CItemCode_ = other.s2CItemCode_;
          onChanged();
        }
        if (other.hasS2CId()) {
          bitField0_ |= 0x00000008;
          s2CId_ = other.s2CId_;
          onChanged();
        }
        if (other.hasS2CParam()) {
          mergeS2CParam(other.getS2CParam());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CCode()) {
          
          return false;
        }
        if (!hasS2CFunGoId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.FunctionHandler.FunctionGoToPush parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.FunctionHandler.FunctionGoToPush) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CCode_ ;
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public boolean hasS2CCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public int getS2CCode() {
        return s2CCode_;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder setS2CCode(int value) {
        bitField0_ |= 0x00000001;
        s2CCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder clearS2CCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CCode_ = 0;
        onChanged();
        return this;
      }

      private int s2CFunGoId_ ;
      /**
       * <code>required int32 s2c_funGoId = 2;</code>
       */
      public boolean hasS2CFunGoId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 s2c_funGoId = 2;</code>
       */
      public int getS2CFunGoId() {
        return s2CFunGoId_;
      }
      /**
       * <code>required int32 s2c_funGoId = 2;</code>
       */
      public Builder setS2CFunGoId(int value) {
        bitField0_ |= 0x00000002;
        s2CFunGoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_funGoId = 2;</code>
       */
      public Builder clearS2CFunGoId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CFunGoId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object s2CItemCode_ = "";
      /**
       * <code>optional string s2c_itemCode = 3;</code>
       */
      public boolean hasS2CItemCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string s2c_itemCode = 3;</code>
       */
      public java.lang.String getS2CItemCode() {
        java.lang.Object ref = s2CItemCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CItemCode_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_itemCode = 3;</code>
       */
      public com.google.protobuf.ByteString
          getS2CItemCodeBytes() {
        java.lang.Object ref = s2CItemCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CItemCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_itemCode = 3;</code>
       */
      public Builder setS2CItemCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s2CItemCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_itemCode = 3;</code>
       */
      public Builder clearS2CItemCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s2CItemCode_ = getDefaultInstance().getS2CItemCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_itemCode = 3;</code>
       */
      public Builder setS2CItemCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        s2CItemCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object s2CId_ = "";
      /**
       * <code>optional string s2c_id = 4;</code>
       */
      public boolean hasS2CId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string s2c_id = 4;</code>
       */
      public java.lang.String getS2CId() {
        java.lang.Object ref = s2CId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_id = 4;</code>
       */
      public com.google.protobuf.ByteString
          getS2CIdBytes() {
        java.lang.Object ref = s2CId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_id = 4;</code>
       */
      public Builder setS2CId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        s2CId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_id = 4;</code>
       */
      public Builder clearS2CId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        s2CId_ = getDefaultInstance().getS2CId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_id = 4;</code>
       */
      public Builder setS2CIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        s2CId_ = value;
        onChanged();
        return this;
      }

      private pomelo.area.FunctionHandler.TipsParam s2CParam_ = pomelo.area.FunctionHandler.TipsParam.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pomelo.area.FunctionHandler.TipsParam, pomelo.area.FunctionHandler.TipsParam.Builder, pomelo.area.FunctionHandler.TipsParamOrBuilder> s2CParamBuilder_;
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public boolean hasS2CParam() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public pomelo.area.FunctionHandler.TipsParam getS2CParam() {
        if (s2CParamBuilder_ == null) {
          return s2CParam_;
        } else {
          return s2CParamBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public Builder setS2CParam(pomelo.area.FunctionHandler.TipsParam value) {
        if (s2CParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2CParam_ = value;
          onChanged();
        } else {
          s2CParamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public Builder setS2CParam(
          pomelo.area.FunctionHandler.TipsParam.Builder builderForValue) {
        if (s2CParamBuilder_ == null) {
          s2CParam_ = builderForValue.build();
          onChanged();
        } else {
          s2CParamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public Builder mergeS2CParam(pomelo.area.FunctionHandler.TipsParam value) {
        if (s2CParamBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              s2CParam_ != pomelo.area.FunctionHandler.TipsParam.getDefaultInstance()) {
            s2CParam_ =
              pomelo.area.FunctionHandler.TipsParam.newBuilder(s2CParam_).mergeFrom(value).buildPartial();
          } else {
            s2CParam_ = value;
          }
          onChanged();
        } else {
          s2CParamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public Builder clearS2CParam() {
        if (s2CParamBuilder_ == null) {
          s2CParam_ = pomelo.area.FunctionHandler.TipsParam.getDefaultInstance();
          onChanged();
        } else {
          s2CParamBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public pomelo.area.FunctionHandler.TipsParam.Builder getS2CParamBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getS2CParamFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      public pomelo.area.FunctionHandler.TipsParamOrBuilder getS2CParamOrBuilder() {
        if (s2CParamBuilder_ != null) {
          return s2CParamBuilder_.getMessageOrBuilder();
        } else {
          return s2CParam_;
        }
      }
      /**
       * <code>optional .pomelo.area.TipsParam s2c_param = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pomelo.area.FunctionHandler.TipsParam, pomelo.area.FunctionHandler.TipsParam.Builder, pomelo.area.FunctionHandler.TipsParamOrBuilder> 
          getS2CParamFieldBuilder() {
        if (s2CParamBuilder_ == null) {
          s2CParamBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pomelo.area.FunctionHandler.TipsParam, pomelo.area.FunctionHandler.TipsParam.Builder, pomelo.area.FunctionHandler.TipsParamOrBuilder>(
                  getS2CParam(),
                  getParentForChildren(),
                  isClean());
          s2CParam_ = null;
        }
        return s2CParamBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.FunctionGoToPush)
    }

    static {
      defaultInstance = new FunctionGoToPush(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.FunctionGoToPush)
  }

  public interface TaskGuideFuncPushOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.TaskGuideFuncPush)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    boolean hasS2CCode();
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    int getS2CCode();

    /**
     * <code>required int32 s2c_taskFuncId = 2;</code>
     */
    boolean hasS2CTaskFuncId();
    /**
     * <code>required int32 s2c_taskFuncId = 2;</code>
     */
    int getS2CTaskFuncId();
  }
  /**
   * Protobuf type {@code pomelo.area.TaskGuideFuncPush}
   */
  public static final class TaskGuideFuncPush extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.TaskGuideFuncPush)
      TaskGuideFuncPushOrBuilder {
    // Use TaskGuideFuncPush.newBuilder() to construct.
    private TaskGuideFuncPush(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TaskGuideFuncPush(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TaskGuideFuncPush defaultInstance;
    public static TaskGuideFuncPush getDefaultInstance() {
      return defaultInstance;
    }

    public TaskGuideFuncPush getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TaskGuideFuncPush(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              s2CTaskFuncId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.FunctionHandler.internal_static_pomelo_area_TaskGuideFuncPush_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.FunctionHandler.internal_static_pomelo_area_TaskGuideFuncPush_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.FunctionHandler.TaskGuideFuncPush.class, pomelo.area.FunctionHandler.TaskGuideFuncPush.Builder.class);
    }

    public static com.google.protobuf.Parser<TaskGuideFuncPush> PARSER =
        new com.google.protobuf.AbstractParser<TaskGuideFuncPush>() {
      public TaskGuideFuncPush parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskGuideFuncPush(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaskGuideFuncPush> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_CODE_FIELD_NUMBER = 1;
    private int s2CCode_;
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public boolean hasS2CCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public int getS2CCode() {
      return s2CCode_;
    }

    public static final int S2C_TASKFUNCID_FIELD_NUMBER = 2;
    private int s2CTaskFuncId_;
    /**
     * <code>required int32 s2c_taskFuncId = 2;</code>
     */
    public boolean hasS2CTaskFuncId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 s2c_taskFuncId = 2;</code>
     */
    public int getS2CTaskFuncId() {
      return s2CTaskFuncId_;
    }

    private void initFields() {
      s2CCode_ = 0;
      s2CTaskFuncId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasS2CTaskFuncId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, s2CTaskFuncId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, s2CTaskFuncId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.FunctionHandler.TaskGuideFuncPush parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.FunctionHandler.TaskGuideFuncPush prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.TaskGuideFuncPush}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.TaskGuideFuncPush)
        pomelo.area.FunctionHandler.TaskGuideFuncPushOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_TaskGuideFuncPush_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_TaskGuideFuncPush_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.FunctionHandler.TaskGuideFuncPush.class, pomelo.area.FunctionHandler.TaskGuideFuncPush.Builder.class);
      }

      // Construct using pomelo.area.FunctionHandler.TaskGuideFuncPush.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CTaskFuncId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.FunctionHandler.internal_static_pomelo_area_TaskGuideFuncPush_descriptor;
      }

      public pomelo.area.FunctionHandler.TaskGuideFuncPush getDefaultInstanceForType() {
        return pomelo.area.FunctionHandler.TaskGuideFuncPush.getDefaultInstance();
      }

      public pomelo.area.FunctionHandler.TaskGuideFuncPush build() {
        pomelo.area.FunctionHandler.TaskGuideFuncPush result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.FunctionHandler.TaskGuideFuncPush buildPartial() {
        pomelo.area.FunctionHandler.TaskGuideFuncPush result = new pomelo.area.FunctionHandler.TaskGuideFuncPush(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CCode_ = s2CCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CTaskFuncId_ = s2CTaskFuncId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.FunctionHandler.TaskGuideFuncPush) {
          return mergeFrom((pomelo.area.FunctionHandler.TaskGuideFuncPush)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.FunctionHandler.TaskGuideFuncPush other) {
        if (other == pomelo.area.FunctionHandler.TaskGuideFuncPush.getDefaultInstance()) return this;
        if (other.hasS2CCode()) {
          setS2CCode(other.getS2CCode());
        }
        if (other.hasS2CTaskFuncId()) {
          setS2CTaskFuncId(other.getS2CTaskFuncId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CCode()) {
          
          return false;
        }
        if (!hasS2CTaskFuncId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.FunctionHandler.TaskGuideFuncPush parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.FunctionHandler.TaskGuideFuncPush) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CCode_ ;
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public boolean hasS2CCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public int getS2CCode() {
        return s2CCode_;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder setS2CCode(int value) {
        bitField0_ |= 0x00000001;
        s2CCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder clearS2CCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CCode_ = 0;
        onChanged();
        return this;
      }

      private int s2CTaskFuncId_ ;
      /**
       * <code>required int32 s2c_taskFuncId = 2;</code>
       */
      public boolean hasS2CTaskFuncId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 s2c_taskFuncId = 2;</code>
       */
      public int getS2CTaskFuncId() {
        return s2CTaskFuncId_;
      }
      /**
       * <code>required int32 s2c_taskFuncId = 2;</code>
       */
      public Builder setS2CTaskFuncId(int value) {
        bitField0_ |= 0x00000002;
        s2CTaskFuncId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_taskFuncId = 2;</code>
       */
      public Builder clearS2CTaskFuncId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CTaskFuncId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.TaskGuideFuncPush)
    }

    static {
      defaultInstance = new TaskGuideFuncPush(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.TaskGuideFuncPush)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_TipsParam_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_TipsParam_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_FunctionGoToPush_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_FunctionGoToPush_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_TaskGuideFuncPush_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_TaskGuideFuncPush_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025functionHandler.proto\022\013pomelo.area\032\014co" +
      "mmon.proto\"\034\n\tTipsParam\022\017\n\007diamond\030\001 \001(\005" +
      "\"\212\001\n\020FunctionGoToPush\022\020\n\010s2c_code\030\001 \002(\005\022" +
      "\023\n\013s2c_funGoId\030\002 \002(\005\022\024\n\014s2c_itemCode\030\003 \001" +
      "(\t\022\016\n\006s2c_id\030\004 \001(\t\022)\n\ts2c_param\030\005 \001(\0132\026." +
      "pomelo.area.TipsParam\"=\n\021TaskGuideFuncPu" +
      "sh\022\020\n\010s2c_code\030\001 \002(\005\022\026\n\016s2c_taskFuncId\030\002" +
      " \002(\0052\021\n\017functionHandler2\222\001\n\014functionPush" +
      "\022?\n\020functionGoToPush\022\035.pomelo.area.Funct" +
      "ionGoToPush\032\014.pomelo.Void\022A\n\021taskGuideFu",
      "ncPush\022\036.pomelo.area.TaskGuideFuncPush\032\014" +
      ".pomelo.Void"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pomelo.Common.getDescriptor(),
        }, assigner);
    internal_static_pomelo_area_TipsParam_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pomelo_area_TipsParam_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_TipsParam_descriptor,
        new java.lang.String[] { "Diamond", });
    internal_static_pomelo_area_FunctionGoToPush_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pomelo_area_FunctionGoToPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_FunctionGoToPush_descriptor,
        new java.lang.String[] { "S2CCode", "S2CFunGoId", "S2CItemCode", "S2CId", "S2CParam", });
    internal_static_pomelo_area_TaskGuideFuncPush_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pomelo_area_TaskGuideFuncPush_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_TaskGuideFuncPush_descriptor,
        new java.lang.String[] { "S2CCode", "S2CTaskFuncId", });
    pomelo.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
