// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: giftOnlineHandler.proto

package pomelo.area;

public final class GiftOnlineHandler {
  private GiftOnlineHandler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetOnLineGiftRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.GetOnLineGiftRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code pomelo.area.GetOnLineGiftRequest}
   */
  public static final class GetOnLineGiftRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.GetOnLineGiftRequest)
      GetOnLineGiftRequestOrBuilder {
    // Use GetOnLineGiftRequest.newBuilder() to construct.
    private GetOnLineGiftRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetOnLineGiftRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetOnLineGiftRequest defaultInstance;
    public static GetOnLineGiftRequest getDefaultInstance() {
      return defaultInstance;
    }

    public GetOnLineGiftRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetOnLineGiftRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.class, pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<GetOnLineGiftRequest> PARSER =
        new com.google.protobuf.AbstractParser<GetOnLineGiftRequest>() {
      public GetOnLineGiftRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetOnLineGiftRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetOnLineGiftRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.GetOnLineGiftRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.GetOnLineGiftRequest)
        pomelo.area.GiftOnlineHandler.GetOnLineGiftRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.class, pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.Builder.class);
      }

      // Construct using pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftRequest_descriptor;
      }

      public pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest getDefaultInstanceForType() {
        return pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.getDefaultInstance();
      }

      public pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest build() {
        pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest buildPartial() {
        pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest result = new pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest) {
          return mergeFrom((pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest other) {
        if (other == pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.GiftOnlineHandler.GetOnLineGiftRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.GetOnLineGiftRequest)
    }

    static {
      defaultInstance = new GetOnLineGiftRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.GetOnLineGiftRequest)
  }

  public interface GiftOnLineStructOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.GiftOnLineStruct)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 templateId = 1;</code>
     */
    boolean hasTemplateId();
    /**
     * <code>required int32 templateId = 1;</code>
     */
    int getTemplateId();

    /**
     * <code>required int32 count = 2;</code>
     */
    boolean hasCount();
    /**
     * <code>required int32 count = 2;</code>
     */
    int getCount();

    /**
     * <code>required int32 quality = 3;</code>
     */
    boolean hasQuality();
    /**
     * <code>required int32 quality = 3;</code>
     */
    int getQuality();

    /**
     * <code>required int32 picId = 4;</code>
     */
    boolean hasPicId();
    /**
     * <code>required int32 picId = 4;</code>
     */
    int getPicId();

    /**
     * <code>required string name = 5;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 5;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 5;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code pomelo.area.GiftOnLineStruct}
   */
  public static final class GiftOnLineStruct extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.GiftOnLineStruct)
      GiftOnLineStructOrBuilder {
    // Use GiftOnLineStruct.newBuilder() to construct.
    private GiftOnLineStruct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GiftOnLineStruct(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GiftOnLineStruct defaultInstance;
    public static GiftOnLineStruct getDefaultInstance() {
      return defaultInstance;
    }

    public GiftOnLineStruct getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GiftOnLineStruct(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              templateId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              quality_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              picId_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnLineStruct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnLineStruct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.GiftOnlineHandler.GiftOnLineStruct.class, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder.class);
    }

    public static com.google.protobuf.Parser<GiftOnLineStruct> PARSER =
        new com.google.protobuf.AbstractParser<GiftOnLineStruct>() {
      public GiftOnLineStruct parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GiftOnLineStruct(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GiftOnLineStruct> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TEMPLATEID_FIELD_NUMBER = 1;
    private int templateId_;
    /**
     * <code>required int32 templateId = 1;</code>
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 templateId = 1;</code>
     */
    public int getTemplateId() {
      return templateId_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>required int32 count = 2;</code>
     */
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 count = 2;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int QUALITY_FIELD_NUMBER = 3;
    private int quality_;
    /**
     * <code>required int32 quality = 3;</code>
     */
    public boolean hasQuality() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 quality = 3;</code>
     */
    public int getQuality() {
      return quality_;
    }

    public static final int PICID_FIELD_NUMBER = 4;
    private int picId_;
    /**
     * <code>required int32 picId = 4;</code>
     */
    public boolean hasPicId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 picId = 4;</code>
     */
    public int getPicId() {
      return picId_;
    }

    public static final int NAME_FIELD_NUMBER = 5;
    private java.lang.Object name_;
    /**
     * <code>required string name = 5;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string name = 5;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      templateId_ = 0;
      count_ = 0;
      quality_ = 0;
      picId_ = 0;
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTemplateId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuality()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPicId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, templateId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, quality_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, picId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, templateId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quality_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, picId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnLineStruct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.GiftOnlineHandler.GiftOnLineStruct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.GiftOnLineStruct}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.GiftOnLineStruct)
        pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnLineStruct_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnLineStruct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.GiftOnlineHandler.GiftOnLineStruct.class, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder.class);
      }

      // Construct using pomelo.area.GiftOnlineHandler.GiftOnLineStruct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        templateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        quality_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        picId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnLineStruct_descriptor;
      }

      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct getDefaultInstanceForType() {
        return pomelo.area.GiftOnlineHandler.GiftOnLineStruct.getDefaultInstance();
      }

      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct build() {
        pomelo.area.GiftOnlineHandler.GiftOnLineStruct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct buildPartial() {
        pomelo.area.GiftOnlineHandler.GiftOnLineStruct result = new pomelo.area.GiftOnlineHandler.GiftOnLineStruct(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.templateId_ = templateId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.count_ = count_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.quality_ = quality_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.picId_ = picId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.GiftOnlineHandler.GiftOnLineStruct) {
          return mergeFrom((pomelo.area.GiftOnlineHandler.GiftOnLineStruct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.GiftOnlineHandler.GiftOnLineStruct other) {
        if (other == pomelo.area.GiftOnlineHandler.GiftOnLineStruct.getDefaultInstance()) return this;
        if (other.hasTemplateId()) {
          setTemplateId(other.getTemplateId());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        if (other.hasQuality()) {
          setQuality(other.getQuality());
        }
        if (other.hasPicId()) {
          setPicId(other.getPicId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000010;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTemplateId()) {
          
          return false;
        }
        if (!hasCount()) {
          
          return false;
        }
        if (!hasQuality()) {
          
          return false;
        }
        if (!hasPicId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.GiftOnlineHandler.GiftOnLineStruct parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.GiftOnlineHandler.GiftOnLineStruct) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int templateId_ ;
      /**
       * <code>required int32 templateId = 1;</code>
       */
      public boolean hasTemplateId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 templateId = 1;</code>
       */
      public int getTemplateId() {
        return templateId_;
      }
      /**
       * <code>required int32 templateId = 1;</code>
       */
      public Builder setTemplateId(int value) {
        bitField0_ |= 0x00000001;
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 templateId = 1;</code>
       */
      public Builder clearTemplateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        templateId_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>required int32 count = 2;</code>
       */
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 count = 2;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>required int32 count = 2;</code>
       */
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 count = 2;</code>
       */
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }

      private int quality_ ;
      /**
       * <code>required int32 quality = 3;</code>
       */
      public boolean hasQuality() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 quality = 3;</code>
       */
      public int getQuality() {
        return quality_;
      }
      /**
       * <code>required int32 quality = 3;</code>
       */
      public Builder setQuality(int value) {
        bitField0_ |= 0x00000004;
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quality = 3;</code>
       */
      public Builder clearQuality() {
        bitField0_ = (bitField0_ & ~0x00000004);
        quality_ = 0;
        onChanged();
        return this;
      }

      private int picId_ ;
      /**
       * <code>required int32 picId = 4;</code>
       */
      public boolean hasPicId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 picId = 4;</code>
       */
      public int getPicId() {
        return picId_;
      }
      /**
       * <code>required int32 picId = 4;</code>
       */
      public Builder setPicId(int value) {
        bitField0_ |= 0x00000008;
        picId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 picId = 4;</code>
       */
      public Builder clearPicId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        picId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 5;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string name = 5;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 5;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 5;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 5;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.GiftOnLineStruct)
    }

    static {
      defaultInstance = new GiftOnLineStruct(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.GiftOnLineStruct)
  }

  public interface GiftOnlineDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.GiftOnlineData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_time = 1;</code>
     */
    boolean hasS2CTime();
    /**
     * <code>required int32 s2c_time = 1;</code>
     */
    int getS2CTime();

    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    java.util.List<pomelo.area.GiftOnlineHandler.GiftOnLineStruct> 
        getS2CItemsList();
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    pomelo.area.GiftOnlineHandler.GiftOnLineStruct getS2CItems(int index);
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    int getS2CItemsCount();
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    java.util.List<? extends pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder> 
        getS2CItemsOrBuilderList();
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder getS2CItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pomelo.area.GiftOnlineData}
   */
  public static final class GiftOnlineData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.GiftOnlineData)
      GiftOnlineDataOrBuilder {
    // Use GiftOnlineData.newBuilder() to construct.
    private GiftOnlineData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GiftOnlineData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GiftOnlineData defaultInstance;
    public static GiftOnlineData getDefaultInstance() {
      return defaultInstance;
    }

    public GiftOnlineData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GiftOnlineData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CTime_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                s2CItems_ = new java.util.ArrayList<pomelo.area.GiftOnlineHandler.GiftOnLineStruct>();
                mutable_bitField0_ |= 0x00000002;
              }
              s2CItems_.add(input.readMessage(pomelo.area.GiftOnlineHandler.GiftOnLineStruct.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          s2CItems_ = java.util.Collections.unmodifiableList(s2CItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnlineData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnlineData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.GiftOnlineHandler.GiftOnlineData.class, pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder.class);
    }

    public static com.google.protobuf.Parser<GiftOnlineData> PARSER =
        new com.google.protobuf.AbstractParser<GiftOnlineData>() {
      public GiftOnlineData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GiftOnlineData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GiftOnlineData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_TIME_FIELD_NUMBER = 1;
    private int s2CTime_;
    /**
     * <code>required int32 s2c_time = 1;</code>
     */
    public boolean hasS2CTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_time = 1;</code>
     */
    public int getS2CTime() {
      return s2CTime_;
    }

    public static final int S2C_ITEMS_FIELD_NUMBER = 2;
    private java.util.List<pomelo.area.GiftOnlineHandler.GiftOnLineStruct> s2CItems_;
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    public java.util.List<pomelo.area.GiftOnlineHandler.GiftOnLineStruct> getS2CItemsList() {
      return s2CItems_;
    }
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    public java.util.List<? extends pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder> 
        getS2CItemsOrBuilderList() {
      return s2CItems_;
    }
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    public int getS2CItemsCount() {
      return s2CItems_.size();
    }
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    public pomelo.area.GiftOnlineHandler.GiftOnLineStruct getS2CItems(int index) {
      return s2CItems_.get(index);
    }
    /**
     * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
     */
    public pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder getS2CItemsOrBuilder(
        int index) {
      return s2CItems_.get(index);
    }

    private void initFields() {
      s2CTime_ = 0;
      s2CItems_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getS2CItemsCount(); i++) {
        if (!getS2CItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CTime_);
      }
      for (int i = 0; i < s2CItems_.size(); i++) {
        output.writeMessage(2, s2CItems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CTime_);
      }
      for (int i = 0; i < s2CItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, s2CItems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GiftOnlineData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.GiftOnlineHandler.GiftOnlineData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.GiftOnlineData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.GiftOnlineData)
        pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnlineData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnlineData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.GiftOnlineHandler.GiftOnlineData.class, pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder.class);
      }

      // Construct using pomelo.area.GiftOnlineHandler.GiftOnlineData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (s2CItemsBuilder_ == null) {
          s2CItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          s2CItemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GiftOnlineData_descriptor;
      }

      public pomelo.area.GiftOnlineHandler.GiftOnlineData getDefaultInstanceForType() {
        return pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance();
      }

      public pomelo.area.GiftOnlineHandler.GiftOnlineData build() {
        pomelo.area.GiftOnlineHandler.GiftOnlineData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.GiftOnlineHandler.GiftOnlineData buildPartial() {
        pomelo.area.GiftOnlineHandler.GiftOnlineData result = new pomelo.area.GiftOnlineHandler.GiftOnlineData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CTime_ = s2CTime_;
        if (s2CItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            s2CItems_ = java.util.Collections.unmodifiableList(s2CItems_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.s2CItems_ = s2CItems_;
        } else {
          result.s2CItems_ = s2CItemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.GiftOnlineHandler.GiftOnlineData) {
          return mergeFrom((pomelo.area.GiftOnlineHandler.GiftOnlineData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.GiftOnlineHandler.GiftOnlineData other) {
        if (other == pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance()) return this;
        if (other.hasS2CTime()) {
          setS2CTime(other.getS2CTime());
        }
        if (s2CItemsBuilder_ == null) {
          if (!other.s2CItems_.isEmpty()) {
            if (s2CItems_.isEmpty()) {
              s2CItems_ = other.s2CItems_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureS2CItemsIsMutable();
              s2CItems_.addAll(other.s2CItems_);
            }
            onChanged();
          }
        } else {
          if (!other.s2CItems_.isEmpty()) {
            if (s2CItemsBuilder_.isEmpty()) {
              s2CItemsBuilder_.dispose();
              s2CItemsBuilder_ = null;
              s2CItems_ = other.s2CItems_;
              bitField0_ = (bitField0_ & ~0x00000002);
              s2CItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getS2CItemsFieldBuilder() : null;
            } else {
              s2CItemsBuilder_.addAllMessages(other.s2CItems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CTime()) {
          
          return false;
        }
        for (int i = 0; i < getS2CItemsCount(); i++) {
          if (!getS2CItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.GiftOnlineHandler.GiftOnlineData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.GiftOnlineHandler.GiftOnlineData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CTime_ ;
      /**
       * <code>required int32 s2c_time = 1;</code>
       */
      public boolean hasS2CTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_time = 1;</code>
       */
      public int getS2CTime() {
        return s2CTime_;
      }
      /**
       * <code>required int32 s2c_time = 1;</code>
       */
      public Builder setS2CTime(int value) {
        bitField0_ |= 0x00000001;
        s2CTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_time = 1;</code>
       */
      public Builder clearS2CTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CTime_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pomelo.area.GiftOnlineHandler.GiftOnLineStruct> s2CItems_ =
        java.util.Collections.emptyList();
      private void ensureS2CItemsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          s2CItems_ = new java.util.ArrayList<pomelo.area.GiftOnlineHandler.GiftOnLineStruct>(s2CItems_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.area.GiftOnlineHandler.GiftOnLineStruct, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder, pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder> s2CItemsBuilder_;

      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public java.util.List<pomelo.area.GiftOnlineHandler.GiftOnLineStruct> getS2CItemsList() {
        if (s2CItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(s2CItems_);
        } else {
          return s2CItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public int getS2CItemsCount() {
        if (s2CItemsBuilder_ == null) {
          return s2CItems_.size();
        } else {
          return s2CItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct getS2CItems(int index) {
        if (s2CItemsBuilder_ == null) {
          return s2CItems_.get(index);
        } else {
          return s2CItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder setS2CItems(
          int index, pomelo.area.GiftOnlineHandler.GiftOnLineStruct value) {
        if (s2CItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureS2CItemsIsMutable();
          s2CItems_.set(index, value);
          onChanged();
        } else {
          s2CItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder setS2CItems(
          int index, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder builderForValue) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          s2CItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder addS2CItems(pomelo.area.GiftOnlineHandler.GiftOnLineStruct value) {
        if (s2CItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureS2CItemsIsMutable();
          s2CItems_.add(value);
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder addS2CItems(
          int index, pomelo.area.GiftOnlineHandler.GiftOnLineStruct value) {
        if (s2CItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureS2CItemsIsMutable();
          s2CItems_.add(index, value);
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder addS2CItems(
          pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder builderForValue) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.add(builderForValue.build());
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder addS2CItems(
          int index, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder builderForValue) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder addAllS2CItems(
          java.lang.Iterable<? extends pomelo.area.GiftOnlineHandler.GiftOnLineStruct> values) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, s2CItems_);
          onChanged();
        } else {
          s2CItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder clearS2CItems() {
        if (s2CItemsBuilder_ == null) {
          s2CItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          s2CItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public Builder removeS2CItems(int index) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.remove(index);
          onChanged();
        } else {
          s2CItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder getS2CItemsBuilder(
          int index) {
        return getS2CItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder getS2CItemsOrBuilder(
          int index) {
        if (s2CItemsBuilder_ == null) {
          return s2CItems_.get(index);  } else {
          return s2CItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public java.util.List<? extends pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder> 
           getS2CItemsOrBuilderList() {
        if (s2CItemsBuilder_ != null) {
          return s2CItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(s2CItems_);
        }
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder addS2CItemsBuilder() {
        return getS2CItemsFieldBuilder().addBuilder(
            pomelo.area.GiftOnlineHandler.GiftOnLineStruct.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder addS2CItemsBuilder(
          int index) {
        return getS2CItemsFieldBuilder().addBuilder(
            index, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.area.GiftOnLineStruct s2c_items = 2;</code>
       */
      public java.util.List<pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder> 
           getS2CItemsBuilderList() {
        return getS2CItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.area.GiftOnlineHandler.GiftOnLineStruct, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder, pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder> 
          getS2CItemsFieldBuilder() {
        if (s2CItemsBuilder_ == null) {
          s2CItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pomelo.area.GiftOnlineHandler.GiftOnLineStruct, pomelo.area.GiftOnlineHandler.GiftOnLineStruct.Builder, pomelo.area.GiftOnlineHandler.GiftOnLineStructOrBuilder>(
                  s2CItems_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          s2CItems_ = null;
        }
        return s2CItemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.GiftOnlineData)
    }

    static {
      defaultInstance = new GiftOnlineData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.GiftOnlineData)
  }

  public interface GetOnLineGiftResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.GetOnLineGiftResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    boolean hasS2CCode();
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    int getS2CCode();

    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    boolean hasS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    java.lang.String getS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getS2CMsgBytes();

    /**
     * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
     */
    boolean hasS2CData();
    /**
     * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
     */
    pomelo.area.GiftOnlineHandler.GiftOnlineData getS2CData();
    /**
     * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
     */
    pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder getS2CDataOrBuilder();
  }
  /**
   * Protobuf type {@code pomelo.area.GetOnLineGiftResponse}
   */
  public static final class GetOnLineGiftResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.GetOnLineGiftResponse)
      GetOnLineGiftResponseOrBuilder {
    // Use GetOnLineGiftResponse.newBuilder() to construct.
    private GetOnLineGiftResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetOnLineGiftResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetOnLineGiftResponse defaultInstance;
    public static GetOnLineGiftResponse getDefaultInstance() {
      return defaultInstance;
    }

    public GetOnLineGiftResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetOnLineGiftResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              s2CMsg_ = bs;
              break;
            }
            case 26: {
              pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = s2CData_.toBuilder();
              }
              s2CData_ = input.readMessage(pomelo.area.GiftOnlineHandler.GiftOnlineData.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2CData_);
                s2CData_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.class, pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<GetOnLineGiftResponse> PARSER =
        new com.google.protobuf.AbstractParser<GetOnLineGiftResponse>() {
      public GetOnLineGiftResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetOnLineGiftResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetOnLineGiftResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_CODE_FIELD_NUMBER = 1;
    private int s2CCode_;
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public boolean hasS2CCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public int getS2CCode() {
      return s2CCode_;
    }

    public static final int S2C_MSG_FIELD_NUMBER = 2;
    private java.lang.Object s2CMsg_;
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public boolean hasS2CMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public java.lang.String getS2CMsg() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getS2CMsgBytes() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_DATA_FIELD_NUMBER = 3;
    private pomelo.area.GiftOnlineHandler.GiftOnlineData s2CData_;
    /**
     * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
     */
    public boolean hasS2CData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
     */
    public pomelo.area.GiftOnlineHandler.GiftOnlineData getS2CData() {
      return s2CData_;
    }
    /**
     * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
     */
    public pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder getS2CDataOrBuilder() {
      return s2CData_;
    }

    private void initFields() {
      s2CCode_ = 0;
      s2CMsg_ = "";
      s2CData_ = pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2CData()) {
        if (!getS2CData().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getS2CMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, s2CData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getS2CMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, s2CData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.GetOnLineGiftResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.GetOnLineGiftResponse)
        pomelo.area.GiftOnlineHandler.GetOnLineGiftResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.class, pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.Builder.class);
      }

      // Construct using pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (s2CDataBuilder_ == null) {
          s2CData_ = pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance();
        } else {
          s2CDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.GiftOnlineHandler.internal_static_pomelo_area_GetOnLineGiftResponse_descriptor;
      }

      public pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse getDefaultInstanceForType() {
        return pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.getDefaultInstance();
      }

      public pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse build() {
        pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse buildPartial() {
        pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse result = new pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CCode_ = s2CCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CMsg_ = s2CMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (s2CDataBuilder_ == null) {
          result.s2CData_ = s2CData_;
        } else {
          result.s2CData_ = s2CDataBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse) {
          return mergeFrom((pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse other) {
        if (other == pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse.getDefaultInstance()) return this;
        if (other.hasS2CCode()) {
          setS2CCode(other.getS2CCode());
        }
        if (other.hasS2CMsg()) {
          bitField0_ |= 0x00000002;
          s2CMsg_ = other.s2CMsg_;
          onChanged();
        }
        if (other.hasS2CData()) {
          mergeS2CData(other.getS2CData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CCode()) {
          
          return false;
        }
        if (hasS2CData()) {
          if (!getS2CData().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.GiftOnlineHandler.GetOnLineGiftResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CCode_ ;
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public boolean hasS2CCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public int getS2CCode() {
        return s2CCode_;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder setS2CCode(int value) {
        bitField0_ |= 0x00000001;
        s2CCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder clearS2CCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object s2CMsg_ = "";
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public boolean hasS2CMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public java.lang.String getS2CMsg() {
        java.lang.Object ref = s2CMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getS2CMsgBytes() {
        java.lang.Object ref = s2CMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder clearS2CMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CMsg_ = getDefaultInstance().getS2CMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }

      private pomelo.area.GiftOnlineHandler.GiftOnlineData s2CData_ = pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          pomelo.area.GiftOnlineHandler.GiftOnlineData, pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder, pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder> s2CDataBuilder_;
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public boolean hasS2CData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnlineData getS2CData() {
        if (s2CDataBuilder_ == null) {
          return s2CData_;
        } else {
          return s2CDataBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public Builder setS2CData(pomelo.area.GiftOnlineHandler.GiftOnlineData value) {
        if (s2CDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2CData_ = value;
          onChanged();
        } else {
          s2CDataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public Builder setS2CData(
          pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder builderForValue) {
        if (s2CDataBuilder_ == null) {
          s2CData_ = builderForValue.build();
          onChanged();
        } else {
          s2CDataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public Builder mergeS2CData(pomelo.area.GiftOnlineHandler.GiftOnlineData value) {
        if (s2CDataBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              s2CData_ != pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance()) {
            s2CData_ =
              pomelo.area.GiftOnlineHandler.GiftOnlineData.newBuilder(s2CData_).mergeFrom(value).buildPartial();
          } else {
            s2CData_ = value;
          }
          onChanged();
        } else {
          s2CDataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public Builder clearS2CData() {
        if (s2CDataBuilder_ == null) {
          s2CData_ = pomelo.area.GiftOnlineHandler.GiftOnlineData.getDefaultInstance();
          onChanged();
        } else {
          s2CDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder getS2CDataBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getS2CDataFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      public pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder getS2CDataOrBuilder() {
        if (s2CDataBuilder_ != null) {
          return s2CDataBuilder_.getMessageOrBuilder();
        } else {
          return s2CData_;
        }
      }
      /**
       * <code>optional .pomelo.area.GiftOnlineData s2c_data = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          pomelo.area.GiftOnlineHandler.GiftOnlineData, pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder, pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder> 
          getS2CDataFieldBuilder() {
        if (s2CDataBuilder_ == null) {
          s2CDataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              pomelo.area.GiftOnlineHandler.GiftOnlineData, pomelo.area.GiftOnlineHandler.GiftOnlineData.Builder, pomelo.area.GiftOnlineHandler.GiftOnlineDataOrBuilder>(
                  getS2CData(),
                  getParentForChildren(),
                  isClean());
          s2CData_ = null;
        }
        return s2CDataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.GetOnLineGiftResponse)
    }

    static {
      defaultInstance = new GetOnLineGiftResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.GetOnLineGiftResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_GetOnLineGiftRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_GetOnLineGiftRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_GiftOnLineStruct_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_GiftOnLineStruct_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_GiftOnlineData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_GiftOnlineData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_GetOnLineGiftResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_GetOnLineGiftResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027giftOnlineHandler.proto\022\013pomelo.area\"\026" +
      "\n\024GetOnLineGiftRequest\"c\n\020GiftOnLineStru" +
      "ct\022\022\n\ntemplateId\030\001 \002(\005\022\r\n\005count\030\002 \002(\005\022\017\n" +
      "\007quality\030\003 \002(\005\022\r\n\005picId\030\004 \002(\005\022\014\n\004name\030\005 " +
      "\002(\t\"T\n\016GiftOnlineData\022\020\n\010s2c_time\030\001 \002(\005\022" +
      "0\n\ts2c_items\030\002 \003(\0132\035.pomelo.area.GiftOnL" +
      "ineStruct\"i\n\025GetOnLineGiftResponse\022\020\n\010s2" +
      "c_code\030\001 \002(\005\022\017\n\007s2c_msg\030\002 \001(\t\022-\n\010s2c_dat" +
      "a\030\003 \001(\0132\033.pomelo.area.GiftOnlineData2r\n\021" +
      "giftOnlineHandler\022]\n\024getOnLineGiftReques",
      "t\022!.pomelo.area.GetOnLineGiftRequest\032\".p" +
      "omelo.area.GetOnLineGiftResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pomelo_area_GetOnLineGiftRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pomelo_area_GetOnLineGiftRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_GetOnLineGiftRequest_descriptor,
        new java.lang.String[] { });
    internal_static_pomelo_area_GiftOnLineStruct_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pomelo_area_GiftOnLineStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_GiftOnLineStruct_descriptor,
        new java.lang.String[] { "TemplateId", "Count", "Quality", "PicId", "Name", });
    internal_static_pomelo_area_GiftOnlineData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pomelo_area_GiftOnlineData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_GiftOnlineData_descriptor,
        new java.lang.String[] { "S2CTime", "S2CItems", });
    internal_static_pomelo_area_GetOnLineGiftResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_pomelo_area_GetOnLineGiftResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_GetOnLineGiftResponse_descriptor,
        new java.lang.String[] { "S2CCode", "S2CMsg", "S2CData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
