// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: npcHandler.proto

package pomelo.area;

public final class NpcHandler {
  private NpcHandler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RecoverByNpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.RecoverByNpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string npcObjId = 1;</code>
     */
    boolean hasNpcObjId();
    /**
     * <code>required string npcObjId = 1;</code>
     */
    java.lang.String getNpcObjId();
    /**
     * <code>required string npcObjId = 1;</code>
     */
    com.google.protobuf.ByteString
        getNpcObjIdBytes();
  }
  /**
   * Protobuf type {@code pomelo.area.RecoverByNpcRequest}
   */
  public static final class RecoverByNpcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.RecoverByNpcRequest)
      RecoverByNpcRequestOrBuilder {
    // Use RecoverByNpcRequest.newBuilder() to construct.
    private RecoverByNpcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RecoverByNpcRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RecoverByNpcRequest defaultInstance;
    public static RecoverByNpcRequest getDefaultInstance() {
      return defaultInstance;
    }

    public RecoverByNpcRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RecoverByNpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              npcObjId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.NpcHandler.RecoverByNpcRequest.class, pomelo.area.NpcHandler.RecoverByNpcRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<RecoverByNpcRequest> PARSER =
        new com.google.protobuf.AbstractParser<RecoverByNpcRequest>() {
      public RecoverByNpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecoverByNpcRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RecoverByNpcRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NPCOBJID_FIELD_NUMBER = 1;
    private java.lang.Object npcObjId_;
    /**
     * <code>required string npcObjId = 1;</code>
     */
    public boolean hasNpcObjId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string npcObjId = 1;</code>
     */
    public java.lang.String getNpcObjId() {
      java.lang.Object ref = npcObjId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          npcObjId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string npcObjId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNpcObjIdBytes() {
      java.lang.Object ref = npcObjId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        npcObjId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      npcObjId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNpcObjId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNpcObjIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNpcObjIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.NpcHandler.RecoverByNpcRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.RecoverByNpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.RecoverByNpcRequest)
        pomelo.area.NpcHandler.RecoverByNpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.NpcHandler.RecoverByNpcRequest.class, pomelo.area.NpcHandler.RecoverByNpcRequest.Builder.class);
      }

      // Construct using pomelo.area.NpcHandler.RecoverByNpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        npcObjId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcRequest_descriptor;
      }

      public pomelo.area.NpcHandler.RecoverByNpcRequest getDefaultInstanceForType() {
        return pomelo.area.NpcHandler.RecoverByNpcRequest.getDefaultInstance();
      }

      public pomelo.area.NpcHandler.RecoverByNpcRequest build() {
        pomelo.area.NpcHandler.RecoverByNpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.NpcHandler.RecoverByNpcRequest buildPartial() {
        pomelo.area.NpcHandler.RecoverByNpcRequest result = new pomelo.area.NpcHandler.RecoverByNpcRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.npcObjId_ = npcObjId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.NpcHandler.RecoverByNpcRequest) {
          return mergeFrom((pomelo.area.NpcHandler.RecoverByNpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.NpcHandler.RecoverByNpcRequest other) {
        if (other == pomelo.area.NpcHandler.RecoverByNpcRequest.getDefaultInstance()) return this;
        if (other.hasNpcObjId()) {
          bitField0_ |= 0x00000001;
          npcObjId_ = other.npcObjId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNpcObjId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.NpcHandler.RecoverByNpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.NpcHandler.RecoverByNpcRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object npcObjId_ = "";
      /**
       * <code>required string npcObjId = 1;</code>
       */
      public boolean hasNpcObjId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string npcObjId = 1;</code>
       */
      public java.lang.String getNpcObjId() {
        java.lang.Object ref = npcObjId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            npcObjId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string npcObjId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNpcObjIdBytes() {
        java.lang.Object ref = npcObjId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          npcObjId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string npcObjId = 1;</code>
       */
      public Builder setNpcObjId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        npcObjId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string npcObjId = 1;</code>
       */
      public Builder clearNpcObjId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        npcObjId_ = getDefaultInstance().getNpcObjId();
        onChanged();
        return this;
      }
      /**
       * <code>required string npcObjId = 1;</code>
       */
      public Builder setNpcObjIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        npcObjId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.RecoverByNpcRequest)
    }

    static {
      defaultInstance = new RecoverByNpcRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.RecoverByNpcRequest)
  }

  public interface RecoverByNpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.RecoverByNpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    boolean hasS2CCode();
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    int getS2CCode();

    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    boolean hasS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    java.lang.String getS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getS2CMsgBytes();
  }
  /**
   * Protobuf type {@code pomelo.area.RecoverByNpcResponse}
   */
  public static final class RecoverByNpcResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.RecoverByNpcResponse)
      RecoverByNpcResponseOrBuilder {
    // Use RecoverByNpcResponse.newBuilder() to construct.
    private RecoverByNpcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RecoverByNpcResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RecoverByNpcResponse defaultInstance;
    public static RecoverByNpcResponse getDefaultInstance() {
      return defaultInstance;
    }

    public RecoverByNpcResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RecoverByNpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              s2CMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.NpcHandler.RecoverByNpcResponse.class, pomelo.area.NpcHandler.RecoverByNpcResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<RecoverByNpcResponse> PARSER =
        new com.google.protobuf.AbstractParser<RecoverByNpcResponse>() {
      public RecoverByNpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecoverByNpcResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RecoverByNpcResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_CODE_FIELD_NUMBER = 1;
    private int s2CCode_;
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public boolean hasS2CCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public int getS2CCode() {
      return s2CCode_;
    }

    public static final int S2C_MSG_FIELD_NUMBER = 2;
    private java.lang.Object s2CMsg_;
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public boolean hasS2CMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public java.lang.String getS2CMsg() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getS2CMsgBytes() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      s2CCode_ = 0;
      s2CMsg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getS2CMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getS2CMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.NpcHandler.RecoverByNpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.NpcHandler.RecoverByNpcResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.RecoverByNpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.RecoverByNpcResponse)
        pomelo.area.NpcHandler.RecoverByNpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.NpcHandler.RecoverByNpcResponse.class, pomelo.area.NpcHandler.RecoverByNpcResponse.Builder.class);
      }

      // Construct using pomelo.area.NpcHandler.RecoverByNpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.NpcHandler.internal_static_pomelo_area_RecoverByNpcResponse_descriptor;
      }

      public pomelo.area.NpcHandler.RecoverByNpcResponse getDefaultInstanceForType() {
        return pomelo.area.NpcHandler.RecoverByNpcResponse.getDefaultInstance();
      }

      public pomelo.area.NpcHandler.RecoverByNpcResponse build() {
        pomelo.area.NpcHandler.RecoverByNpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.NpcHandler.RecoverByNpcResponse buildPartial() {
        pomelo.area.NpcHandler.RecoverByNpcResponse result = new pomelo.area.NpcHandler.RecoverByNpcResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CCode_ = s2CCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CMsg_ = s2CMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.NpcHandler.RecoverByNpcResponse) {
          return mergeFrom((pomelo.area.NpcHandler.RecoverByNpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.NpcHandler.RecoverByNpcResponse other) {
        if (other == pomelo.area.NpcHandler.RecoverByNpcResponse.getDefaultInstance()) return this;
        if (other.hasS2CCode()) {
          setS2CCode(other.getS2CCode());
        }
        if (other.hasS2CMsg()) {
          bitField0_ |= 0x00000002;
          s2CMsg_ = other.s2CMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.NpcHandler.RecoverByNpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.NpcHandler.RecoverByNpcResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CCode_ ;
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public boolean hasS2CCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public int getS2CCode() {
        return s2CCode_;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder setS2CCode(int value) {
        bitField0_ |= 0x00000001;
        s2CCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder clearS2CCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object s2CMsg_ = "";
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public boolean hasS2CMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public java.lang.String getS2CMsg() {
        java.lang.Object ref = s2CMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getS2CMsgBytes() {
        java.lang.Object ref = s2CMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder clearS2CMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CMsg_ = getDefaultInstance().getS2CMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.RecoverByNpcResponse)
    }

    static {
      defaultInstance = new RecoverByNpcResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.RecoverByNpcResponse)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_RecoverByNpcRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_RecoverByNpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_RecoverByNpcResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_RecoverByNpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020npcHandler.proto\022\013pomelo.area\"\'\n\023Recov" +
      "erByNpcRequest\022\020\n\010npcObjId\030\001 \002(\t\"9\n\024Reco" +
      "verByNpcResponse\022\020\n\010s2c_code\030\001 \002(\005\022\017\n\007s2" +
      "c_msg\030\002 \001(\t2h\n\nnpcHandler\022Z\n\023recoverByNp" +
      "cRequest\022 .pomelo.area.RecoverByNpcReque" +
      "st\032!.pomelo.area.RecoverByNpcResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pomelo_area_RecoverByNpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pomelo_area_RecoverByNpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_RecoverByNpcRequest_descriptor,
        new java.lang.String[] { "NpcObjId", });
    internal_static_pomelo_area_RecoverByNpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pomelo_area_RecoverByNpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_RecoverByNpcResponse_descriptor,
        new java.lang.String[] { "S2CCode", "S2CMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
