// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stealHandler.proto

package pomelo.area;

public final class StealHandler {
  private StealHandler() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StealResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.StealResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    boolean hasS2CCode();
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    int getS2CCode();

    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    boolean hasS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    java.lang.String getS2CMsg();
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getS2CMsgBytes();

    /**
     * <code>optional int32 s2c_result = 3;</code>
     */
    boolean hasS2CResult();
    /**
     * <code>optional int32 s2c_result = 3;</code>
     */
    int getS2CResult();

    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    java.util.List<pomelo.item.ItemOuterClass.MiniItem> 
        getS2CItemsList();
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    pomelo.item.ItemOuterClass.MiniItem getS2CItems(int index);
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    int getS2CItemsCount();
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    java.util.List<? extends pomelo.item.ItemOuterClass.MiniItemOrBuilder> 
        getS2CItemsOrBuilderList();
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    pomelo.item.ItemOuterClass.MiniItemOrBuilder getS2CItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pomelo.area.StealResponse}
   */
  public static final class StealResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.StealResponse)
      StealResponseOrBuilder {
    // Use StealResponse.newBuilder() to construct.
    private StealResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StealResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StealResponse defaultInstance;
    public static StealResponse getDefaultInstance() {
      return defaultInstance;
    }

    public StealResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StealResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              s2CCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              s2CMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              s2CResult_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                s2CItems_ = new java.util.ArrayList<pomelo.item.ItemOuterClass.MiniItem>();
                mutable_bitField0_ |= 0x00000008;
              }
              s2CItems_.add(input.readMessage(pomelo.item.ItemOuterClass.MiniItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          s2CItems_ = java.util.Collections.unmodifiableList(s2CItems_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.StealHandler.internal_static_pomelo_area_StealResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.StealHandler.internal_static_pomelo_area_StealResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.StealHandler.StealResponse.class, pomelo.area.StealHandler.StealResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<StealResponse> PARSER =
        new com.google.protobuf.AbstractParser<StealResponse>() {
      public StealResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StealResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StealResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int S2C_CODE_FIELD_NUMBER = 1;
    private int s2CCode_;
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public boolean hasS2CCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 s2c_code = 1;</code>
     */
    public int getS2CCode() {
      return s2CCode_;
    }

    public static final int S2C_MSG_FIELD_NUMBER = 2;
    private java.lang.Object s2CMsg_;
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public boolean hasS2CMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public java.lang.String getS2CMsg() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          s2CMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string s2c_msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getS2CMsgBytes() {
      java.lang.Object ref = s2CMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s2CMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int S2C_RESULT_FIELD_NUMBER = 3;
    private int s2CResult_;
    /**
     * <code>optional int32 s2c_result = 3;</code>
     */
    public boolean hasS2CResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 s2c_result = 3;</code>
     */
    public int getS2CResult() {
      return s2CResult_;
    }

    public static final int S2C_ITEMS_FIELD_NUMBER = 4;
    private java.util.List<pomelo.item.ItemOuterClass.MiniItem> s2CItems_;
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    public java.util.List<pomelo.item.ItemOuterClass.MiniItem> getS2CItemsList() {
      return s2CItems_;
    }
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    public java.util.List<? extends pomelo.item.ItemOuterClass.MiniItemOrBuilder> 
        getS2CItemsOrBuilderList() {
      return s2CItems_;
    }
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    public int getS2CItemsCount() {
      return s2CItems_.size();
    }
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    public pomelo.item.ItemOuterClass.MiniItem getS2CItems(int index) {
      return s2CItems_.get(index);
    }
    /**
     * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
     */
    public pomelo.item.ItemOuterClass.MiniItemOrBuilder getS2CItemsOrBuilder(
        int index) {
      return s2CItems_.get(index);
    }

    private void initFields() {
      s2CCode_ = 0;
      s2CMsg_ = "";
      s2CResult_ = 0;
      s2CItems_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasS2CCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getS2CItemsCount(); i++) {
        if (!getS2CItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getS2CMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, s2CResult_);
      }
      for (int i = 0; i < s2CItems_.size(); i++) {
        output.writeMessage(4, s2CItems_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, s2CCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getS2CMsgBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, s2CResult_);
      }
      for (int i = 0; i < s2CItems_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, s2CItems_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.StealHandler.StealResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.StealHandler.StealResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.StealHandler.StealResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.StealHandler.StealResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.StealResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.StealResponse)
        pomelo.area.StealHandler.StealResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.StealHandler.internal_static_pomelo_area_StealResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.StealHandler.internal_static_pomelo_area_StealResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.StealHandler.StealResponse.class, pomelo.area.StealHandler.StealResponse.Builder.class);
      }

      // Construct using pomelo.area.StealHandler.StealResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getS2CItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        s2CCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CResult_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CItemsBuilder_ == null) {
          s2CItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          s2CItemsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.StealHandler.internal_static_pomelo_area_StealResponse_descriptor;
      }

      public pomelo.area.StealHandler.StealResponse getDefaultInstanceForType() {
        return pomelo.area.StealHandler.StealResponse.getDefaultInstance();
      }

      public pomelo.area.StealHandler.StealResponse build() {
        pomelo.area.StealHandler.StealResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.StealHandler.StealResponse buildPartial() {
        pomelo.area.StealHandler.StealResponse result = new pomelo.area.StealHandler.StealResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.s2CCode_ = s2CCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.s2CMsg_ = s2CMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.s2CResult_ = s2CResult_;
        if (s2CItemsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            s2CItems_ = java.util.Collections.unmodifiableList(s2CItems_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.s2CItems_ = s2CItems_;
        } else {
          result.s2CItems_ = s2CItemsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.StealHandler.StealResponse) {
          return mergeFrom((pomelo.area.StealHandler.StealResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.StealHandler.StealResponse other) {
        if (other == pomelo.area.StealHandler.StealResponse.getDefaultInstance()) return this;
        if (other.hasS2CCode()) {
          setS2CCode(other.getS2CCode());
        }
        if (other.hasS2CMsg()) {
          bitField0_ |= 0x00000002;
          s2CMsg_ = other.s2CMsg_;
          onChanged();
        }
        if (other.hasS2CResult()) {
          setS2CResult(other.getS2CResult());
        }
        if (s2CItemsBuilder_ == null) {
          if (!other.s2CItems_.isEmpty()) {
            if (s2CItems_.isEmpty()) {
              s2CItems_ = other.s2CItems_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureS2CItemsIsMutable();
              s2CItems_.addAll(other.s2CItems_);
            }
            onChanged();
          }
        } else {
          if (!other.s2CItems_.isEmpty()) {
            if (s2CItemsBuilder_.isEmpty()) {
              s2CItemsBuilder_.dispose();
              s2CItemsBuilder_ = null;
              s2CItems_ = other.s2CItems_;
              bitField0_ = (bitField0_ & ~0x00000008);
              s2CItemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getS2CItemsFieldBuilder() : null;
            } else {
              s2CItemsBuilder_.addAllMessages(other.s2CItems_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasS2CCode()) {
          
          return false;
        }
        for (int i = 0; i < getS2CItemsCount(); i++) {
          if (!getS2CItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.StealHandler.StealResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.StealHandler.StealResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int s2CCode_ ;
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public boolean hasS2CCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public int getS2CCode() {
        return s2CCode_;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder setS2CCode(int value) {
        bitField0_ |= 0x00000001;
        s2CCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 s2c_code = 1;</code>
       */
      public Builder clearS2CCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        s2CCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object s2CMsg_ = "";
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public boolean hasS2CMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public java.lang.String getS2CMsg() {
        java.lang.Object ref = s2CMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            s2CMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getS2CMsgBytes() {
        java.lang.Object ref = s2CMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          s2CMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder clearS2CMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        s2CMsg_ = getDefaultInstance().getS2CMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string s2c_msg = 2;</code>
       */
      public Builder setS2CMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        s2CMsg_ = value;
        onChanged();
        return this;
      }

      private int s2CResult_ ;
      /**
       * <code>optional int32 s2c_result = 3;</code>
       */
      public boolean hasS2CResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 s2c_result = 3;</code>
       */
      public int getS2CResult() {
        return s2CResult_;
      }
      /**
       * <code>optional int32 s2c_result = 3;</code>
       */
      public Builder setS2CResult(int value) {
        bitField0_ |= 0x00000004;
        s2CResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 s2c_result = 3;</code>
       */
      public Builder clearS2CResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        s2CResult_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<pomelo.item.ItemOuterClass.MiniItem> s2CItems_ =
        java.util.Collections.emptyList();
      private void ensureS2CItemsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          s2CItems_ = new java.util.ArrayList<pomelo.item.ItemOuterClass.MiniItem>(s2CItems_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.item.ItemOuterClass.MiniItem, pomelo.item.ItemOuterClass.MiniItem.Builder, pomelo.item.ItemOuterClass.MiniItemOrBuilder> s2CItemsBuilder_;

      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public java.util.List<pomelo.item.ItemOuterClass.MiniItem> getS2CItemsList() {
        if (s2CItemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(s2CItems_);
        } else {
          return s2CItemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public int getS2CItemsCount() {
        if (s2CItemsBuilder_ == null) {
          return s2CItems_.size();
        } else {
          return s2CItemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public pomelo.item.ItemOuterClass.MiniItem getS2CItems(int index) {
        if (s2CItemsBuilder_ == null) {
          return s2CItems_.get(index);
        } else {
          return s2CItemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder setS2CItems(
          int index, pomelo.item.ItemOuterClass.MiniItem value) {
        if (s2CItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureS2CItemsIsMutable();
          s2CItems_.set(index, value);
          onChanged();
        } else {
          s2CItemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder setS2CItems(
          int index, pomelo.item.ItemOuterClass.MiniItem.Builder builderForValue) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.set(index, builderForValue.build());
          onChanged();
        } else {
          s2CItemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder addS2CItems(pomelo.item.ItemOuterClass.MiniItem value) {
        if (s2CItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureS2CItemsIsMutable();
          s2CItems_.add(value);
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder addS2CItems(
          int index, pomelo.item.ItemOuterClass.MiniItem value) {
        if (s2CItemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureS2CItemsIsMutable();
          s2CItems_.add(index, value);
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder addS2CItems(
          pomelo.item.ItemOuterClass.MiniItem.Builder builderForValue) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.add(builderForValue.build());
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder addS2CItems(
          int index, pomelo.item.ItemOuterClass.MiniItem.Builder builderForValue) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.add(index, builderForValue.build());
          onChanged();
        } else {
          s2CItemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder addAllS2CItems(
          java.lang.Iterable<? extends pomelo.item.ItemOuterClass.MiniItem> values) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, s2CItems_);
          onChanged();
        } else {
          s2CItemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder clearS2CItems() {
        if (s2CItemsBuilder_ == null) {
          s2CItems_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          s2CItemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public Builder removeS2CItems(int index) {
        if (s2CItemsBuilder_ == null) {
          ensureS2CItemsIsMutable();
          s2CItems_.remove(index);
          onChanged();
        } else {
          s2CItemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public pomelo.item.ItemOuterClass.MiniItem.Builder getS2CItemsBuilder(
          int index) {
        return getS2CItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public pomelo.item.ItemOuterClass.MiniItemOrBuilder getS2CItemsOrBuilder(
          int index) {
        if (s2CItemsBuilder_ == null) {
          return s2CItems_.get(index);  } else {
          return s2CItemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public java.util.List<? extends pomelo.item.ItemOuterClass.MiniItemOrBuilder> 
           getS2CItemsOrBuilderList() {
        if (s2CItemsBuilder_ != null) {
          return s2CItemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(s2CItems_);
        }
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public pomelo.item.ItemOuterClass.MiniItem.Builder addS2CItemsBuilder() {
        return getS2CItemsFieldBuilder().addBuilder(
            pomelo.item.ItemOuterClass.MiniItem.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public pomelo.item.ItemOuterClass.MiniItem.Builder addS2CItemsBuilder(
          int index) {
        return getS2CItemsFieldBuilder().addBuilder(
            index, pomelo.item.ItemOuterClass.MiniItem.getDefaultInstance());
      }
      /**
       * <code>repeated .pomelo.item.MiniItem s2c_items = 4;</code>
       */
      public java.util.List<pomelo.item.ItemOuterClass.MiniItem.Builder> 
           getS2CItemsBuilderList() {
        return getS2CItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          pomelo.item.ItemOuterClass.MiniItem, pomelo.item.ItemOuterClass.MiniItem.Builder, pomelo.item.ItemOuterClass.MiniItemOrBuilder> 
          getS2CItemsFieldBuilder() {
        if (s2CItemsBuilder_ == null) {
          s2CItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              pomelo.item.ItemOuterClass.MiniItem, pomelo.item.ItemOuterClass.MiniItem.Builder, pomelo.item.ItemOuterClass.MiniItemOrBuilder>(
                  s2CItems_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          s2CItems_ = null;
        }
        return s2CItemsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.StealResponse)
    }

    static {
      defaultInstance = new StealResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.StealResponse)
  }

  public interface StealRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pomelo.area.StealRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 c2s_id = 1;</code>
     */
    boolean hasC2SId();
    /**
     * <code>required int32 c2s_id = 1;</code>
     */
    int getC2SId();
  }
  /**
   * Protobuf type {@code pomelo.area.StealRequest}
   */
  public static final class StealRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:pomelo.area.StealRequest)
      StealRequestOrBuilder {
    // Use StealRequest.newBuilder() to construct.
    private StealRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StealRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StealRequest defaultInstance;
    public static StealRequest getDefaultInstance() {
      return defaultInstance;
    }

    public StealRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StealRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              c2SId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pomelo.area.StealHandler.internal_static_pomelo_area_StealRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pomelo.area.StealHandler.internal_static_pomelo_area_StealRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pomelo.area.StealHandler.StealRequest.class, pomelo.area.StealHandler.StealRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<StealRequest> PARSER =
        new com.google.protobuf.AbstractParser<StealRequest>() {
      public StealRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StealRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StealRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int C2S_ID_FIELD_NUMBER = 1;
    private int c2SId_;
    /**
     * <code>required int32 c2s_id = 1;</code>
     */
    public boolean hasC2SId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 c2s_id = 1;</code>
     */
    public int getC2SId() {
      return c2SId_;
    }

    private void initFields() {
      c2SId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasC2SId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, c2SId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, c2SId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static pomelo.area.StealHandler.StealRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static pomelo.area.StealHandler.StealRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static pomelo.area.StealHandler.StealRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pomelo.area.StealHandler.StealRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pomelo.area.StealRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pomelo.area.StealRequest)
        pomelo.area.StealHandler.StealRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pomelo.area.StealHandler.internal_static_pomelo_area_StealRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pomelo.area.StealHandler.internal_static_pomelo_area_StealRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pomelo.area.StealHandler.StealRequest.class, pomelo.area.StealHandler.StealRequest.Builder.class);
      }

      // Construct using pomelo.area.StealHandler.StealRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        c2SId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pomelo.area.StealHandler.internal_static_pomelo_area_StealRequest_descriptor;
      }

      public pomelo.area.StealHandler.StealRequest getDefaultInstanceForType() {
        return pomelo.area.StealHandler.StealRequest.getDefaultInstance();
      }

      public pomelo.area.StealHandler.StealRequest build() {
        pomelo.area.StealHandler.StealRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public pomelo.area.StealHandler.StealRequest buildPartial() {
        pomelo.area.StealHandler.StealRequest result = new pomelo.area.StealHandler.StealRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.c2SId_ = c2SId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pomelo.area.StealHandler.StealRequest) {
          return mergeFrom((pomelo.area.StealHandler.StealRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pomelo.area.StealHandler.StealRequest other) {
        if (other == pomelo.area.StealHandler.StealRequest.getDefaultInstance()) return this;
        if (other.hasC2SId()) {
          setC2SId(other.getC2SId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasC2SId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        pomelo.area.StealHandler.StealRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (pomelo.area.StealHandler.StealRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int c2SId_ ;
      /**
       * <code>required int32 c2s_id = 1;</code>
       */
      public boolean hasC2SId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 c2s_id = 1;</code>
       */
      public int getC2SId() {
        return c2SId_;
      }
      /**
       * <code>required int32 c2s_id = 1;</code>
       */
      public Builder setC2SId(int value) {
        bitField0_ |= 0x00000001;
        c2SId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 c2s_id = 1;</code>
       */
      public Builder clearC2SId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        c2SId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:pomelo.area.StealRequest)
    }

    static {
      defaultInstance = new StealRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:pomelo.area.StealRequest)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_StealResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_StealResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pomelo_area_StealRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_pomelo_area_StealRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022stealHandler.proto\022\013pomelo.area\032\nitem." +
      "proto\"p\n\rStealResponse\022\020\n\010s2c_code\030\001 \002(\005" +
      "\022\017\n\007s2c_msg\030\002 \001(\t\022\022\n\ns2c_result\030\003 \001(\005\022(\n" +
      "\ts2c_items\030\004 \003(\0132\025.pomelo.item.MiniItem\"" +
      "\036\n\014StealRequest\022\016\n\006c2s_id\030\001 \002(\0052U\n\014steal" +
      "Handler\022E\n\014stealRequest\022\031.pomelo.area.St" +
      "ealRequest\032\032.pomelo.area.StealResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pomelo.item.ItemOuterClass.getDescriptor(),
        }, assigner);
    internal_static_pomelo_area_StealResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pomelo_area_StealResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_StealResponse_descriptor,
        new java.lang.String[] { "S2CCode", "S2CMsg", "S2CResult", "S2CItems", });
    internal_static_pomelo_area_StealRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pomelo_area_StealRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_pomelo_area_StealRequest_descriptor,
        new java.lang.String[] { "C2SId", });
    pomelo.item.ItemOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
